// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 3.0.21.
// **********************************************************************

#ifndef __SIPPRX_H_
#define __SIPPRX_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
#include "tup/TarsJson.h"
using namespace std;
#include "SipProxyDb/src/SipDb.h"
#include "servant/ServantProxy.h"
#include "servant/Servant.h"
#include "promise/promise.h"


namespace VoipApp
{
    enum AppAccountStatusType
    {
        kAppAccountStatusInvalid = -1,
        kAppAccountStatusUnRegister = 0,
        kAppAccountStatusRegister = 1,
        kAppAccountStatusReRegister = 2,
        kAppAccountStatusTmpUnRegister = 3,
        kAppAccountStatusTmpRegister = 4,
    };
    inline string etos(const AppAccountStatusType & e)
    {
        switch(e)
        {
            case kAppAccountStatusInvalid: return "kAppAccountStatusInvalid";
            case kAppAccountStatusUnRegister: return "kAppAccountStatusUnRegister";
            case kAppAccountStatusRegister: return "kAppAccountStatusRegister";
            case kAppAccountStatusReRegister: return "kAppAccountStatusReRegister";
            case kAppAccountStatusTmpUnRegister: return "kAppAccountStatusTmpUnRegister";
            case kAppAccountStatusTmpRegister: return "kAppAccountStatusTmpRegister";
            default: return "";
        }
    }
    inline int stoe(const string & s, AppAccountStatusType & e)
    {
        if(s == "kAppAccountStatusInvalid")  { e=kAppAccountStatusInvalid; return 0;}
        if(s == "kAppAccountStatusUnRegister")  { e=kAppAccountStatusUnRegister; return 0;}
        if(s == "kAppAccountStatusRegister")  { e=kAppAccountStatusRegister; return 0;}
        if(s == "kAppAccountStatusReRegister")  { e=kAppAccountStatusReRegister; return 0;}
        if(s == "kAppAccountStatusTmpUnRegister")  { e=kAppAccountStatusTmpUnRegister; return 0;}
        if(s == "kAppAccountStatusTmpRegister")  { e=kAppAccountStatusTmpRegister; return 0;}

        return -1;
    }

    struct SipAccount : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "VoipApp.SipAccount";
        }
        static string MD5()
        {
            return "0c1d945735360d4e3752e1b2d448ba0c";
        }
        SipAccount()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            _sipAccount = "";
            _password = "";
            _appUserAccount = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(_sipAccount, 0);
            _os.write(_password, 1);
            _os.write(_appUserAccount, 2);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(_sipAccount, 0, true);
            _is.read(_password, 1, true);
            _is.read(_appUserAccount, 2, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["_sipAccount"] = tars::JsonOutput::writeJson(_sipAccount);
            p->value["_password"] = tars::JsonOutput::writeJson(_password);
            p->value["_appUserAccount"] = tars::JsonOutput::writeJson(_appUserAccount);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(_sipAccount,pObj->value["_sipAccount"], true);
            tars::JsonInput::readJson(_password,pObj->value["_password"], true);
            tars::JsonInput::readJson(_appUserAccount,pObj->value["_appUserAccount"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(_sipAccount,"_sipAccount");
            _ds.display(_password,"_password");
            _ds.display(_appUserAccount,"_appUserAccount");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(_sipAccount, true);
            _ds.displaySimple(_password, true);
            _ds.displaySimple(_appUserAccount, false);
            return _os;
        }
    public:
        std::string _sipAccount;
        std::string _password;
        std::string _appUserAccount;
    };
    inline bool operator==(const SipAccount&l, const SipAccount&r)
    {
        return l._sipAccount == r._sipAccount && l._password == r._password && l._appUserAccount == r._appUserAccount;
    }
    inline bool operator!=(const SipAccount&l, const SipAccount&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const SipAccount&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,SipAccount&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct SipAccount2 : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "VoipApp.SipAccount2";
        }
        static string MD5()
        {
            return "55420b345e13da84aad635417b0d3f4b";
        }
        SipAccount2()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            _sipAccount = "";
            _password = "";
            _appUserAccount = "";
            _authName = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(_sipAccount, 0);
            _os.write(_password, 1);
            _os.write(_appUserAccount, 2);
            _os.write(_authName, 3);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(_sipAccount, 0, true);
            _is.read(_password, 1, true);
            _is.read(_appUserAccount, 2, true);
            _is.read(_authName, 3, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["_sipAccount"] = tars::JsonOutput::writeJson(_sipAccount);
            p->value["_password"] = tars::JsonOutput::writeJson(_password);
            p->value["_appUserAccount"] = tars::JsonOutput::writeJson(_appUserAccount);
            p->value["_authName"] = tars::JsonOutput::writeJson(_authName);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(_sipAccount,pObj->value["_sipAccount"], true);
            tars::JsonInput::readJson(_password,pObj->value["_password"], true);
            tars::JsonInput::readJson(_appUserAccount,pObj->value["_appUserAccount"], true);
            tars::JsonInput::readJson(_authName,pObj->value["_authName"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(_sipAccount,"_sipAccount");
            _ds.display(_password,"_password");
            _ds.display(_appUserAccount,"_appUserAccount");
            _ds.display(_authName,"_authName");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(_sipAccount, true);
            _ds.displaySimple(_password, true);
            _ds.displaySimple(_appUserAccount, true);
            _ds.displaySimple(_authName, false);
            return _os;
        }
    public:
        std::string _sipAccount;
        std::string _password;
        std::string _appUserAccount;
        std::string _authName;
    };
    inline bool operator==(const SipAccount2&l, const SipAccount2&r)
    {
        return l._sipAccount == r._sipAccount && l._password == r._password && l._appUserAccount == r._appUserAccount && l._authName == r._authName;
    }
    inline bool operator!=(const SipAccount2&l, const SipAccount2&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const SipAccount2&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,SipAccount2&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct AppAccountStatusNotify : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "VoipApp.AppAccountStatusNotify";
        }
        static string MD5()
        {
            return "7aee4298010fd8b85159181dd0998ccc";
        }
        AppAccountStatusNotify()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            _sipAccount.resetDefautlt();
            _statusType = VoipApp::kAppAccountStatusInvalid;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(_sipAccount, 0);
            _os.write((tars::Int32)_statusType, 1);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(_sipAccount, 0, true);
            tars::Int32 eTemp1 = VoipApp::kAppAccountStatusInvalid;
            _is.read(eTemp1, 1, true);
            _statusType = (VoipApp::AppAccountStatusType)eTemp1;
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["_sipAccount"] = tars::JsonOutput::writeJson(_sipAccount);
            p->value["_statusType"] = tars::JsonOutput::writeJson((tars::Int32)_statusType);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(_sipAccount,pObj->value["_sipAccount"], true);
            tars::JsonInput::readJson(_statusType,pObj->value["_statusType"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(_sipAccount,"_sipAccount");
            _ds.display((tars::Int32)_statusType,"_statusType");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(_sipAccount, true);
            _ds.displaySimple((tars::Int32)_statusType, false);
            return _os;
        }
    public:
        VoipApp::SipAccountInfo _sipAccount;
        VoipApp::AppAccountStatusType _statusType;
    };
    inline bool operator==(const AppAccountStatusNotify&l, const AppAccountStatusNotify&r)
    {
        return l._sipAccount == r._sipAccount && l._statusType == r._statusType;
    }
    inline bool operator!=(const AppAccountStatusNotify&l, const AppAccountStatusNotify&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const AppAccountStatusNotify&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,AppAccountStatusNotify&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct HttpNotify : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "VoipApp.HttpNotify";
        }
        static string MD5()
        {
            return "352ba5c80384b731bb29eb5cc5f2545a";
        }
        HttpNotify()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            time = 0;
            from = "";
            to = "";
            domain = "";
            type = 0;
            msg = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(time, 0);
            _os.write(from, 1);
            _os.write(to, 2);
            _os.write(domain, 3);
            _os.write(type, 4);
            _os.write(msg, 5);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(time, 0, true);
            _is.read(from, 1, true);
            _is.read(to, 2, true);
            _is.read(domain, 3, true);
            _is.read(type, 4, true);
            _is.read(msg, 5, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["time"] = tars::JsonOutput::writeJson(time);
            p->value["from"] = tars::JsonOutput::writeJson(from);
            p->value["to"] = tars::JsonOutput::writeJson(to);
            p->value["domain"] = tars::JsonOutput::writeJson(domain);
            p->value["type"] = tars::JsonOutput::writeJson(type);
            p->value["msg"] = tars::JsonOutput::writeJson(msg);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(time,pObj->value["time"], true);
            tars::JsonInput::readJson(from,pObj->value["from"], true);
            tars::JsonInput::readJson(to,pObj->value["to"], true);
            tars::JsonInput::readJson(domain,pObj->value["domain"], true);
            tars::JsonInput::readJson(type,pObj->value["type"], true);
            tars::JsonInput::readJson(msg,pObj->value["msg"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(time,"time");
            _ds.display(from,"from");
            _ds.display(to,"to");
            _ds.display(domain,"domain");
            _ds.display(type,"type");
            _ds.display(msg,"msg");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(time, true);
            _ds.displaySimple(from, true);
            _ds.displaySimple(to, true);
            _ds.displaySimple(domain, true);
            _ds.displaySimple(type, true);
            _ds.displaySimple(msg, false);
            return _os;
        }
    public:
        tars::Int64 time;
        std::string from;
        std::string to;
        std::string domain;
        tars::Int32 type;
        std::string msg;
    };
    inline bool operator==(const HttpNotify&l, const HttpNotify&r)
    {
        return l.time == r.time && l.from == r.from && l.to == r.to && l.domain == r.domain && l.type == r.type && l.msg == r.msg;
    }
    inline bool operator!=(const HttpNotify&l, const HttpNotify&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const HttpNotify&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,HttpNotify&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct HttpNotifyRequest : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "VoipApp.HttpNotifyRequest";
        }
        static string MD5()
        {
            return "1d9d2372b06a87b0294839a485a30d16";
        }
        HttpNotifyRequest()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            seq = 0;
            msgList.clear();
            params.clear();
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(seq, 0);
            _os.write(msgList, 1);
            _os.write(params, 2);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(seq, 0, true);
            _is.read(msgList, 1, true);
            _is.read(params, 2, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["seq"] = tars::JsonOutput::writeJson(seq);
            p->value["msgList"] = tars::JsonOutput::writeJson(msgList);
            p->value["params"] = tars::JsonOutput::writeJson(params);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(seq,pObj->value["seq"], true);
            tars::JsonInput::readJson(msgList,pObj->value["msgList"], true);
            tars::JsonInput::readJson(params,pObj->value["params"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(seq,"seq");
            _ds.display(msgList,"msgList");
            _ds.display(params,"params");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(seq, true);
            _ds.displaySimple(msgList, true);
            _ds.displaySimple(params, false);
            return _os;
        }
    public:
        tars::Int32 seq;
        vector<VoipApp::HttpNotify> msgList;
        map<std::string, std::string> params;
    };
    inline bool operator==(const HttpNotifyRequest&l, const HttpNotifyRequest&r)
    {
        return l.seq == r.seq && l.msgList == r.msgList && l.params == r.params;
    }
    inline bool operator!=(const HttpNotifyRequest&l, const HttpNotifyRequest&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const HttpNotifyRequest&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,HttpNotifyRequest&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }


    /* callback of async proxy for client */
    class SipPrxPrxCallback: public tars::ServantProxyCallback
    {
    public:
        virtual ~SipPrxPrxCallback(){}
        virtual void callback_test(tars::Int32 ret)
        { throw std::runtime_error("callback_test() override incorrect."); }
        virtual void callback_test_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_test_exception() override incorrect."); }

    public:
        virtual const map<std::string, std::string> & getResponseContext() const
        {
            CallbackThreadData * pCbtd = CallbackThreadData::getData();
            assert(pCbtd != NULL);

            if(!pCbtd->getContextValid())
            {
                throw TC_Exception("cann't get response context");
            }
            return pCbtd->getResponseContext();
        }

    public:
        virtual int onDispatch(tars::ReqMessagePtr _msg_)
        {
            static ::std::string __SipPrx_all[]=
            {
                "test"
            };
            auto it = _msg_->response->status.find("TARS_FUNC");
            pair<string*, string*> r = equal_range(__SipPrx_all, __SipPrx_all+1, (it==_msg_->response->status.end())?_msg_->request.sFuncName:it->second);
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __SipPrx_all)
            {
                case 0:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_test_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
                    if (_pSptd_ && _pSptd_->_traceCall)
                    {
                        string _trace_param_;
                        int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CR, _is.size());
                        if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                        {
                            tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                            _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                            _trace_param_ = tars::TC_Json::writeValue(_p_);
                        }
                        else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                        {
                            _trace_param_ = "{\"trace_param_over_max_len\":true}";
                        }
                        TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CR), TRACE_ANNOTATION_CR, "", getModuleName(), "test", 0, _trace_param_, "");
                    }

                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(_msg_->response->context);

                    callback_test(_ret);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<SipPrxPrxCallback> SipPrxPrxCallbackPtr;

    //callback of promise async proxy for client
    class SipPrxPrxCallbackPromise: public tars::ServantProxyCallback
    {
    public:
        virtual ~SipPrxPrxCallbackPromise(){}
    public:
        struct Promisetest: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< SipPrxPrxCallbackPromise::Promisetest > PromisetestPtr;

        SipPrxPrxCallbackPromise(const tars::Promise< SipPrxPrxCallbackPromise::PromisetestPtr > &promise)
        : _promise_test(promise)
        {}
        
        virtual void callback_test(const SipPrxPrxCallbackPromise::PromisetestPtr &ptr)
        {
            _promise_test.setValue(ptr);
        }
        virtual void callback_test_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:test_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_test.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< SipPrxPrxCallbackPromise::PromisetestPtr > _promise_test;

    public:
        virtual int onDispatch(tars::ReqMessagePtr _msg_)
        {
            static ::std::string __SipPrx_all[]=
            {
                "test"
            };

            pair<string*, string*> r = equal_range(__SipPrx_all, __SipPrx_all+1, string(_msg_->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __SipPrx_all)
            {
                case 0:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_test_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);

                    SipPrxPrxCallbackPromise::PromisetestPtr ptr (new SipPrxPrxCallbackPromise::Promisetest());

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                    }
                    catch(std::exception &ex)
                    {
                        callback_test_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_test_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = _msg_->response->context;

                    callback_test(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<SipPrxPrxCallbackPromise> SipPrxPrxCallbackPromisePtr;

    /* callback of coroutine async proxy for client */
    class SipPrxCoroPrxCallback: public SipPrxPrxCallback
    {
    public:
        virtual ~SipPrxCoroPrxCallback(){}
    public:
        virtual const map<std::string, std::string> & getResponseContext() const { return _mRspContext; }

        virtual void setResponseContext(const map<std::string, std::string> &mContext) { _mRspContext = mContext; }

    public:
        int onDispatch(tars::ReqMessagePtr _msg_)
        {
            static ::std::string __SipPrx_all[]=
            {
                "test"
            };

            pair<string*, string*> r = equal_range(__SipPrx_all, __SipPrx_all+1, string(_msg_->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __SipPrx_all)
            {
                case 0:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_test_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        setResponseContext(_msg_->response->context);

                        callback_test(_ret);

                    }
                    catch(std::exception &ex)
                    {
                        callback_test_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_test_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    protected:
        map<std::string, std::string> _mRspContext;
    };
    typedef tars::TC_AutoPtr<SipPrxCoroPrxCallback> SipPrxCoroPrxCallbackPtr;

    /* proxy for client */
    class SipPrxProxy : public tars::ServantProxy
    {
    public:
        typedef map<string, string> TARS_CONTEXT;
        tars::Int32 test(const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                _pSptd_->newSpan();
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CS, _os.getLength());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CS), TRACE_ANNOTATION_CS, tars_moduleName(), tars_name(), "test", 0, _trace_param_, "");
            }

            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"test", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CR, _is.size());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CR), TRACE_ANNOTATION_CR, tars_moduleName(), tars_name(), "test", 0, _trace_param_, "");
            }

            return _ret;
        }

        void async_test(SipPrxPrxCallbackPtr callback,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            std::map<string, string> _mStatus;
            ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                _pSptd_->newSpan();
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CS, _os.getLength());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CS), TRACE_ANNOTATION_CS, tars_moduleName(), tars_name(), "test", 0, _trace_param_, "");
            }
            tars_invoke_async(tars::TARSNORMAL,"test", _os, context, _mStatus, callback);
        }
        
        tars::Future< SipPrxPrxCallbackPromise::PromisetestPtr > promise_async_test(const map<string, string>& context)
        {
            tars::Promise< SipPrxPrxCallbackPromise::PromisetestPtr > promise;
            SipPrxPrxCallbackPromisePtr callback (new SipPrxPrxCallbackPromise(promise));

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"test", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_test(SipPrxCoroPrxCallbackPtr callback,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"test", _os, context, _mStatus, callback, true);
        }

        SipPrxProxy* tars_hash(size_t key)
        {
            return (SipPrxProxy*)ServantProxy::tars_hash(key);
        }

        SipPrxProxy* tars_consistent_hash(size_t key)
        {
            return (SipPrxProxy*)ServantProxy::tars_consistent_hash(key);
        }

        SipPrxProxy* tars_open_trace(bool traceParam = false)
        {
            return (SipPrxProxy*)ServantProxy::tars_open_trace(traceParam);
        }

        SipPrxProxy* tars_set_timeout(int msecond)
        {
            return (SipPrxProxy*)ServantProxy::tars_set_timeout(msecond);
        }

        static const char* tars_prxname() { return "SipPrxProxy"; }
    };
    typedef tars::TC_AutoPtr<SipPrxProxy> SipPrxPrx;

    /* servant for server */
    class SipPrx : public tars::Servant
    {
    public:
        virtual ~SipPrx(){}
        virtual tars::Int32 test(tars::TarsCurrentPtr _current_) = 0;
        static void async_response_test(tars::TarsCurrentPtr _current_, tars::Int32 _ret)
        {
            size_t _rsp_len_ = 0;
            if (_current_->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                _tarsAttr_.setVersion(_current_->getRequestVersion());
                _tarsAttr_.put("", _ret);
                _tarsAttr_.put("tars_ret", _ret);

                vector<char> sTupResponseBuffer;
                _tarsAttr_.encode(sTupResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, _tarsAttr_);
                _rsp_len_ = sTupResponseBuffer.size();
            }
            else if (_current_->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
                _rsp_len_ = sJsonResponseBuffer.size();
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _rsp_len_ = _os.getLength();
                _current_->sendResponse(tars::TARSSERVERSUCCESS, _os);
            }
            if (_current_->isTraced())
            {
                string _trace_param_;
                int _trace_param_flag_ = ServantProxyThreadData::needTraceParam(ServantProxyThreadData::TraceContext::EST_SS, _current_->getTraceKey(), _rsp_len_);
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                if(_current_->getServantHandle())
                {
                    TARS_TRACE(_current_->getTraceKey(), TRACE_ANNOTATION_SS, "", _current_->getModuleName(), "test", 0, _trace_param_, "");
                }
            }

        }
        static void async_response_push_test(tars::CurrentPtr _current_, tars::Int32 _ret, const map<string, string> &_context = tars::Current::TARS_STATUS())
        {
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _current_->sendPushResponse( tars::TARSSERVERSUCCESS ,"test", _os, _context);
            }
        }

    public:
        int onDispatch(tars::TarsCurrentPtr _current, vector<char> &_sResponseBuffer)
        {
            static ::std::string __VoipApp__SipPrx_all[]=
            {
                "test"
            };

            pair<string*, string*> r = equal_range(__VoipApp__SipPrx_all, __VoipApp__SipPrx_all+1, _current->getFuncName());
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __VoipApp__SipPrx_all)
            {
                case 0:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                        _tarsAttr_.setVersion(_current->getRequestVersion());
                        _tarsAttr_.decode(_current->getRequestBuffer());
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                    }
                    else
                    {
                    }
                    ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
                    if (_pSptd_ && _pSptd_->_traceCall)
                    {
                        string _trace_param_;
                        int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_SR, _is.size());
                        if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                        {
                            tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                            _trace_param_ = tars::TC_Json::writeValue(_p_);
                        }
                        else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                        {
                            _trace_param_ = "{\"trace_param_over_max_len\":true}";
                        }
                        TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SR), TRACE_ANNOTATION_SR, "", getModuleName(), "test", 0, _trace_param_, "");
                    }

                    tars::Int32 _ret = test(_current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                            _tarsAttr_.setVersion(_current->getRequestVersion());
                            _tarsAttr_.put("", _ret);
                            _tarsAttr_.put("tars_ret", _ret);
                            _tarsAttr_.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.swap(_sResponseBuffer);
                        }
                        if (_pSptd_ && _pSptd_->_traceCall)
                        {
                            string _trace_param_;
                            int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_SS, _sResponseBuffer.size());
                            if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                            {
                                tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                                _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                                _trace_param_ = tars::TC_Json::writeValue(_p_);
                            }
                            else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                            {
                                _trace_param_ = "{\"trace_param_over_max_len\":true}";
                            }
                            TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SS), TRACE_ANNOTATION_SS, "", getModuleName(), "test", 0, _trace_param_, "");
                        }

                    }
                    else if(_pSptd_ && _pSptd_->_traceCall)
                    {
                        _current->setTrace(_pSptd_->_traceCall, _pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SS));
                    }

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }
    };


}



#endif
