// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 3.0.21.
// **********************************************************************

#ifndef __SIPRELAY_H_
#define __SIPRELAY_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
#include "tup/TarsJson.h"
using namespace std;
#include "servant/ServantProxy.h"
#include "servant/Servant.h"
#include "promise/promise.h"


namespace VoipApp
{

    /* callback of async proxy for client */
    class SipRelayPrxCallback: public tars::ServantProxyCallback
    {
    public:
        virtual ~SipRelayPrxCallback(){}
        virtual void callback_eraseSipDlgIdAndConnection(tars::Bool ret)
        { throw std::runtime_error("callback_eraseSipDlgIdAndConnection() override incorrect."); }
        virtual void callback_eraseSipDlgIdAndConnection_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_eraseSipDlgIdAndConnection_exception() override incorrect."); }

        virtual void callback_getIntranetIp(tars::Bool ret,  const std::string& mgcfSipGatewayOid,  const std::string& intranetIp)
        { throw std::runtime_error("callback_getIntranetIp() override incorrect."); }
        virtual void callback_getIntranetIp_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_getIntranetIp_exception() override incorrect."); }
        virtual void callback_getIntranetIp(tars::Bool ret, std::string&&  mgcfSipGatewayOid, std::string&&  intranetIp)
        { callback_getIntranetIp(ret, mgcfSipGatewayOid, intranetIp); }

        virtual void callback_getMgcfConnectStatus(tars::Bool ret,  const std::string& mgcfSipGatewayOid,  const map<std::string, std::string>& params)
        { throw std::runtime_error("callback_getMgcfConnectStatus() override incorrect."); }
        virtual void callback_getMgcfConnectStatus_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_getMgcfConnectStatus_exception() override incorrect."); }
        virtual void callback_getMgcfConnectStatus(tars::Bool ret, std::string&&  mgcfSipGatewayOid, map<std::string, std::string>&&  params)
        { callback_getMgcfConnectStatus(ret, mgcfSipGatewayOid, params); }

        virtual void callback_recvSipMsgFromCloudSipGateway(tars::Bool ret)
        { throw std::runtime_error("callback_recvSipMsgFromCloudSipGateway() override incorrect."); }
        virtual void callback_recvSipMsgFromCloudSipGateway_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_recvSipMsgFromCloudSipGateway_exception() override incorrect."); }

    public:
        virtual const map<std::string, std::string> & getResponseContext() const
        {
            CallbackThreadData * pCbtd = CallbackThreadData::getData();
            assert(pCbtd != NULL);

            if(!pCbtd->getContextValid())
            {
                throw TC_Exception("cann't get response context");
            }
            return pCbtd->getResponseContext();
        }

    public:
        virtual int onDispatch(tars::ReqMessagePtr _msg_)
        {
            static ::std::string __SipRelay_all[]=
            {
                "eraseSipDlgIdAndConnection",
                "getIntranetIp",
                "getMgcfConnectStatus",
                "recvSipMsgFromCloudSipGateway"
            };
            auto it = _msg_->response->status.find("TARS_FUNC");
            pair<string*, string*> r = equal_range(__SipRelay_all, __SipRelay_all+4, (it==_msg_->response->status.end())?_msg_->request.sFuncName:it->second);
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __SipRelay_all)
            {
                case 0:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_eraseSipDlgIdAndConnection_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    tars::Bool _ret = false;
                    _is.read(_ret, 0, true);

                    ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
                    if (_pSptd_ && _pSptd_->_traceCall)
                    {
                        string _trace_param_;
                        int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CR, _is.size());
                        if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                        {
                            tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                            _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                            _trace_param_ = tars::TC_Json::writeValue(_p_);
                        }
                        else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                        {
                            _trace_param_ = "{\"trace_param_over_max_len\":true}";
                        }
                        TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CR), TRACE_ANNOTATION_CR, "", getModuleName(), "eraseSipDlgIdAndConnection", 0, _trace_param_, "");
                    }

                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(_msg_->response->context);

                    callback_eraseSipDlgIdAndConnection(_ret);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_getIntranetIp_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    tars::Bool _ret = false;
                    _is.read(_ret, 0, true);

                    std::string mgcfSipGatewayOid;
                    _is.read(mgcfSipGatewayOid, 2, true);
                    std::string intranetIp;
                    _is.read(intranetIp, 3, true);
                    ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
                    if (_pSptd_ && _pSptd_->_traceCall)
                    {
                        string _trace_param_;
                        int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CR, _is.size());
                        if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                        {
                            tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                            _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                            _p_->value["mgcfSipGatewayOid"] = tars::JsonOutput::writeJson(mgcfSipGatewayOid);
                            _p_->value["intranetIp"] = tars::JsonOutput::writeJson(intranetIp);
                            _trace_param_ = tars::TC_Json::writeValue(_p_);
                        }
                        else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                        {
                            _trace_param_ = "{\"trace_param_over_max_len\":true}";
                        }
                        TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CR), TRACE_ANNOTATION_CR, "", getModuleName(), "getIntranetIp", 0, _trace_param_, "");
                    }

                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(_msg_->response->context);

                    callback_getIntranetIp(_ret, std::move(mgcfSipGatewayOid), std::move(intranetIp));

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_getMgcfConnectStatus_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    tars::Bool _ret = false;
                    _is.read(_ret, 0, true);

                    std::string mgcfSipGatewayOid;
                    _is.read(mgcfSipGatewayOid, 2, true);
                    map<std::string, std::string> params;
                    _is.read(params, 3, true);
                    ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
                    if (_pSptd_ && _pSptd_->_traceCall)
                    {
                        string _trace_param_;
                        int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CR, _is.size());
                        if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                        {
                            tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                            _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                            _p_->value["mgcfSipGatewayOid"] = tars::JsonOutput::writeJson(mgcfSipGatewayOid);
                            _p_->value["params"] = tars::JsonOutput::writeJson(params);
                            _trace_param_ = tars::TC_Json::writeValue(_p_);
                        }
                        else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                        {
                            _trace_param_ = "{\"trace_param_over_max_len\":true}";
                        }
                        TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CR), TRACE_ANNOTATION_CR, "", getModuleName(), "getMgcfConnectStatus", 0, _trace_param_, "");
                    }

                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(_msg_->response->context);

                    callback_getMgcfConnectStatus(_ret, std::move(mgcfSipGatewayOid), std::move(params));

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_recvSipMsgFromCloudSipGateway_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    tars::Bool _ret = false;
                    _is.read(_ret, 0, true);

                    ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
                    if (_pSptd_ && _pSptd_->_traceCall)
                    {
                        string _trace_param_;
                        int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CR, _is.size());
                        if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                        {
                            tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                            _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                            _trace_param_ = tars::TC_Json::writeValue(_p_);
                        }
                        else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                        {
                            _trace_param_ = "{\"trace_param_over_max_len\":true}";
                        }
                        TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CR), TRACE_ANNOTATION_CR, "", getModuleName(), "recvSipMsgFromCloudSipGateway", 0, _trace_param_, "");
                    }

                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(_msg_->response->context);

                    callback_recvSipMsgFromCloudSipGateway(_ret);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<SipRelayPrxCallback> SipRelayPrxCallbackPtr;

    //callback of promise async proxy for client
    class SipRelayPrxCallbackPromise: public tars::ServantProxyCallback
    {
    public:
        virtual ~SipRelayPrxCallbackPromise(){}
    public:
        struct PromiseeraseSipDlgIdAndConnection: virtual public TC_HandleBase
        {
        public:
            tars::Bool _ret;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< SipRelayPrxCallbackPromise::PromiseeraseSipDlgIdAndConnection > PromiseeraseSipDlgIdAndConnectionPtr;

        SipRelayPrxCallbackPromise(const tars::Promise< SipRelayPrxCallbackPromise::PromiseeraseSipDlgIdAndConnectionPtr > &promise)
        : _promise_eraseSipDlgIdAndConnection(promise)
        {}
        
        virtual void callback_eraseSipDlgIdAndConnection(const SipRelayPrxCallbackPromise::PromiseeraseSipDlgIdAndConnectionPtr &ptr)
        {
            _promise_eraseSipDlgIdAndConnection.setValue(ptr);
        }
        virtual void callback_eraseSipDlgIdAndConnection_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:eraseSipDlgIdAndConnection_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_eraseSipDlgIdAndConnection.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< SipRelayPrxCallbackPromise::PromiseeraseSipDlgIdAndConnectionPtr > _promise_eraseSipDlgIdAndConnection;

    public:
        struct PromisegetIntranetIp: virtual public TC_HandleBase
        {
        public:
            tars::Bool _ret;
            std::string mgcfSipGatewayOid;
            std::string intranetIp;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< SipRelayPrxCallbackPromise::PromisegetIntranetIp > PromisegetIntranetIpPtr;

        SipRelayPrxCallbackPromise(const tars::Promise< SipRelayPrxCallbackPromise::PromisegetIntranetIpPtr > &promise)
        : _promise_getIntranetIp(promise)
        {}
        
        virtual void callback_getIntranetIp(const SipRelayPrxCallbackPromise::PromisegetIntranetIpPtr &ptr)
        {
            _promise_getIntranetIp.setValue(ptr);
        }
        virtual void callback_getIntranetIp_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:getIntranetIp_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_getIntranetIp.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< SipRelayPrxCallbackPromise::PromisegetIntranetIpPtr > _promise_getIntranetIp;

    public:
        struct PromisegetMgcfConnectStatus: virtual public TC_HandleBase
        {
        public:
            tars::Bool _ret;
            std::string mgcfSipGatewayOid;
            map<std::string, std::string> params;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< SipRelayPrxCallbackPromise::PromisegetMgcfConnectStatus > PromisegetMgcfConnectStatusPtr;

        SipRelayPrxCallbackPromise(const tars::Promise< SipRelayPrxCallbackPromise::PromisegetMgcfConnectStatusPtr > &promise)
        : _promise_getMgcfConnectStatus(promise)
        {}
        
        virtual void callback_getMgcfConnectStatus(const SipRelayPrxCallbackPromise::PromisegetMgcfConnectStatusPtr &ptr)
        {
            _promise_getMgcfConnectStatus.setValue(ptr);
        }
        virtual void callback_getMgcfConnectStatus_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:getMgcfConnectStatus_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_getMgcfConnectStatus.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< SipRelayPrxCallbackPromise::PromisegetMgcfConnectStatusPtr > _promise_getMgcfConnectStatus;

    public:
        struct PromiserecvSipMsgFromCloudSipGateway: virtual public TC_HandleBase
        {
        public:
            tars::Bool _ret;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< SipRelayPrxCallbackPromise::PromiserecvSipMsgFromCloudSipGateway > PromiserecvSipMsgFromCloudSipGatewayPtr;

        SipRelayPrxCallbackPromise(const tars::Promise< SipRelayPrxCallbackPromise::PromiserecvSipMsgFromCloudSipGatewayPtr > &promise)
        : _promise_recvSipMsgFromCloudSipGateway(promise)
        {}
        
        virtual void callback_recvSipMsgFromCloudSipGateway(const SipRelayPrxCallbackPromise::PromiserecvSipMsgFromCloudSipGatewayPtr &ptr)
        {
            _promise_recvSipMsgFromCloudSipGateway.setValue(ptr);
        }
        virtual void callback_recvSipMsgFromCloudSipGateway_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:recvSipMsgFromCloudSipGateway_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_recvSipMsgFromCloudSipGateway.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< SipRelayPrxCallbackPromise::PromiserecvSipMsgFromCloudSipGatewayPtr > _promise_recvSipMsgFromCloudSipGateway;

    public:
        virtual int onDispatch(tars::ReqMessagePtr _msg_)
        {
            static ::std::string __SipRelay_all[]=
            {
                "eraseSipDlgIdAndConnection",
                "getIntranetIp",
                "getMgcfConnectStatus",
                "recvSipMsgFromCloudSipGateway"
            };

            pair<string*, string*> r = equal_range(__SipRelay_all, __SipRelay_all+4, string(_msg_->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __SipRelay_all)
            {
                case 0:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_eraseSipDlgIdAndConnection_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);

                    SipRelayPrxCallbackPromise::PromiseeraseSipDlgIdAndConnectionPtr ptr (new SipRelayPrxCallbackPromise::PromiseeraseSipDlgIdAndConnection());

                    try
                    {
                        ptr->_ret  = false;
                        _is.read(ptr->_ret, 0, true);

                    }
                    catch(std::exception &ex)
                    {
                        callback_eraseSipDlgIdAndConnection_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_eraseSipDlgIdAndConnection_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = _msg_->response->context;

                    callback_eraseSipDlgIdAndConnection(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_getIntranetIp_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);

                    SipRelayPrxCallbackPromise::PromisegetIntranetIpPtr ptr (new SipRelayPrxCallbackPromise::PromisegetIntranetIp());

                    try
                    {
                        ptr->_ret  = false;
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->mgcfSipGatewayOid, 2, true);
                        _is.read(ptr->intranetIp, 3, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_getIntranetIp_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_getIntranetIp_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = _msg_->response->context;

                    callback_getIntranetIp(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_getMgcfConnectStatus_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);

                    SipRelayPrxCallbackPromise::PromisegetMgcfConnectStatusPtr ptr (new SipRelayPrxCallbackPromise::PromisegetMgcfConnectStatus());

                    try
                    {
                        ptr->_ret  = false;
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->mgcfSipGatewayOid, 2, true);
                        _is.read(ptr->params, 3, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_getMgcfConnectStatus_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_getMgcfConnectStatus_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = _msg_->response->context;

                    callback_getMgcfConnectStatus(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_recvSipMsgFromCloudSipGateway_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);

                    SipRelayPrxCallbackPromise::PromiserecvSipMsgFromCloudSipGatewayPtr ptr (new SipRelayPrxCallbackPromise::PromiserecvSipMsgFromCloudSipGateway());

                    try
                    {
                        ptr->_ret  = false;
                        _is.read(ptr->_ret, 0, true);

                    }
                    catch(std::exception &ex)
                    {
                        callback_recvSipMsgFromCloudSipGateway_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_recvSipMsgFromCloudSipGateway_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = _msg_->response->context;

                    callback_recvSipMsgFromCloudSipGateway(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<SipRelayPrxCallbackPromise> SipRelayPrxCallbackPromisePtr;

    /* callback of coroutine async proxy for client */
    class SipRelayCoroPrxCallback: public SipRelayPrxCallback
    {
    public:
        virtual ~SipRelayCoroPrxCallback(){}
    public:
        virtual const map<std::string, std::string> & getResponseContext() const { return _mRspContext; }

        virtual void setResponseContext(const map<std::string, std::string> &mContext) { _mRspContext = mContext; }

    public:
        int onDispatch(tars::ReqMessagePtr _msg_)
        {
            static ::std::string __SipRelay_all[]=
            {
                "eraseSipDlgIdAndConnection",
                "getIntranetIp",
                "getMgcfConnectStatus",
                "recvSipMsgFromCloudSipGateway"
            };

            pair<string*, string*> r = equal_range(__SipRelay_all, __SipRelay_all+4, string(_msg_->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __SipRelay_all)
            {
                case 0:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_eraseSipDlgIdAndConnection_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    try
                    {
                        tars::Bool _ret = false;
                        _is.read(_ret, 0, true);

                        setResponseContext(_msg_->response->context);

                        callback_eraseSipDlgIdAndConnection(_ret);

                    }
                    catch(std::exception &ex)
                    {
                        callback_eraseSipDlgIdAndConnection_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_eraseSipDlgIdAndConnection_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_getIntranetIp_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    try
                    {
                        tars::Bool _ret = false;
                        _is.read(_ret, 0, true);

                        std::string mgcfSipGatewayOid;
                        _is.read(mgcfSipGatewayOid, 2, true);
                        std::string intranetIp;
                        _is.read(intranetIp, 3, true);
                        setResponseContext(_msg_->response->context);

                        callback_getIntranetIp(_ret, std::move(mgcfSipGatewayOid), std::move(intranetIp));

                    }
                    catch(std::exception &ex)
                    {
                        callback_getIntranetIp_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_getIntranetIp_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_getMgcfConnectStatus_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    try
                    {
                        tars::Bool _ret = false;
                        _is.read(_ret, 0, true);

                        std::string mgcfSipGatewayOid;
                        _is.read(mgcfSipGatewayOid, 2, true);
                        map<std::string, std::string> params;
                        _is.read(params, 3, true);
                        setResponseContext(_msg_->response->context);

                        callback_getMgcfConnectStatus(_ret, std::move(mgcfSipGatewayOid), std::move(params));

                    }
                    catch(std::exception &ex)
                    {
                        callback_getMgcfConnectStatus_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_getMgcfConnectStatus_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_recvSipMsgFromCloudSipGateway_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    try
                    {
                        tars::Bool _ret = false;
                        _is.read(_ret, 0, true);

                        setResponseContext(_msg_->response->context);

                        callback_recvSipMsgFromCloudSipGateway(_ret);

                    }
                    catch(std::exception &ex)
                    {
                        callback_recvSipMsgFromCloudSipGateway_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_recvSipMsgFromCloudSipGateway_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    protected:
        map<std::string, std::string> _mRspContext;
    };
    typedef tars::TC_AutoPtr<SipRelayCoroPrxCallback> SipRelayCoroPrxCallbackPtr;

    /* proxy for client */
    class SipRelayProxy : public tars::ServantProxy
    {
    public:
        typedef map<string, string> TARS_CONTEXT;
        tars::Bool eraseSipDlgIdAndConnection(const std::string & sipGatewayId,const std::string & dialogId,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(sipGatewayId, 1);
            _os.write(dialogId, 2);
            ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                _pSptd_->newSpan();
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CS, _os.getLength());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value["sipGatewayId"] = tars::JsonOutput::writeJson(sipGatewayId);
                    _p_->value["dialogId"] = tars::JsonOutput::writeJson(dialogId);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CS), TRACE_ANNOTATION_CS, tars_moduleName(), tars_name(), "eraseSipDlgIdAndConnection", 0, _trace_param_, "");
            }

            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"eraseSipDlgIdAndConnection", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Bool _ret = false;
            _is.read(_ret, 0, true);
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CR, _is.size());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CR), TRACE_ANNOTATION_CR, tars_moduleName(), tars_name(), "eraseSipDlgIdAndConnection", 0, _trace_param_, "");
            }

            return _ret;
        }

        void async_eraseSipDlgIdAndConnection(SipRelayPrxCallbackPtr callback,const std::string &sipGatewayId,const std::string &dialogId,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(sipGatewayId, 1);
            _os.write(dialogId, 2);
            std::map<string, string> _mStatus;
            ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                _pSptd_->newSpan();
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CS, _os.getLength());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value["sipGatewayId"] = tars::JsonOutput::writeJson(sipGatewayId);
                    _p_->value["dialogId"] = tars::JsonOutput::writeJson(dialogId);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CS), TRACE_ANNOTATION_CS, tars_moduleName(), tars_name(), "eraseSipDlgIdAndConnection", 0, _trace_param_, "");
            }
            tars_invoke_async(tars::TARSNORMAL,"eraseSipDlgIdAndConnection", _os, context, _mStatus, callback);
        }
        
        tars::Future< SipRelayPrxCallbackPromise::PromiseeraseSipDlgIdAndConnectionPtr > promise_async_eraseSipDlgIdAndConnection(const std::string &sipGatewayId,const std::string &dialogId,const map<string, string>& context)
        {
            tars::Promise< SipRelayPrxCallbackPromise::PromiseeraseSipDlgIdAndConnectionPtr > promise;
            SipRelayPrxCallbackPromisePtr callback (new SipRelayPrxCallbackPromise(promise));

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(sipGatewayId, 1);
            _os.write(dialogId, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"eraseSipDlgIdAndConnection", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_eraseSipDlgIdAndConnection(SipRelayCoroPrxCallbackPtr callback,const std::string &sipGatewayId,const std::string &dialogId,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(sipGatewayId, 1);
            _os.write(dialogId, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"eraseSipDlgIdAndConnection", _os, context, _mStatus, callback, true);
        }

        tars::Bool getIntranetIp(const std::string & sipGatewayId,std::string &mgcfSipGatewayOid,std::string &intranetIp,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(sipGatewayId, 1);
            _os.write(mgcfSipGatewayOid, 2);
            _os.write(intranetIp, 3);
            ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                _pSptd_->newSpan();
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CS, _os.getLength());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value["sipGatewayId"] = tars::JsonOutput::writeJson(sipGatewayId);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CS), TRACE_ANNOTATION_CS, tars_moduleName(), tars_name(), "getIntranetIp", 0, _trace_param_, "");
            }

            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"getIntranetIp", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Bool _ret = false;
            _is.read(_ret, 0, true);
            _is.read(mgcfSipGatewayOid, 2, true);
            _is.read(intranetIp, 3, true);
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CR, _is.size());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                    _p_->value["mgcfSipGatewayOid"] = tars::JsonOutput::writeJson(mgcfSipGatewayOid);
                    _p_->value["intranetIp"] = tars::JsonOutput::writeJson(intranetIp);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CR), TRACE_ANNOTATION_CR, tars_moduleName(), tars_name(), "getIntranetIp", 0, _trace_param_, "");
            }

            return _ret;
        }

        void async_getIntranetIp(SipRelayPrxCallbackPtr callback,const std::string &sipGatewayId,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(sipGatewayId, 1);
            std::map<string, string> _mStatus;
            ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                _pSptd_->newSpan();
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CS, _os.getLength());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value["sipGatewayId"] = tars::JsonOutput::writeJson(sipGatewayId);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CS), TRACE_ANNOTATION_CS, tars_moduleName(), tars_name(), "getIntranetIp", 0, _trace_param_, "");
            }
            tars_invoke_async(tars::TARSNORMAL,"getIntranetIp", _os, context, _mStatus, callback);
        }
        
        tars::Future< SipRelayPrxCallbackPromise::PromisegetIntranetIpPtr > promise_async_getIntranetIp(const std::string &sipGatewayId,const map<string, string>& context)
        {
            tars::Promise< SipRelayPrxCallbackPromise::PromisegetIntranetIpPtr > promise;
            SipRelayPrxCallbackPromisePtr callback (new SipRelayPrxCallbackPromise(promise));

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(sipGatewayId, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"getIntranetIp", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_getIntranetIp(SipRelayCoroPrxCallbackPtr callback,const std::string &sipGatewayId,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(sipGatewayId, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"getIntranetIp", _os, context, _mStatus, callback, true);
        }

        tars::Bool getMgcfConnectStatus(const std::string & sipGatewayId,std::string &mgcfSipGatewayOid,map<std::string, std::string> &params,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(sipGatewayId, 1);
            _os.write(mgcfSipGatewayOid, 2);
            _os.write(params, 3);
            ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                _pSptd_->newSpan();
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CS, _os.getLength());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value["sipGatewayId"] = tars::JsonOutput::writeJson(sipGatewayId);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CS), TRACE_ANNOTATION_CS, tars_moduleName(), tars_name(), "getMgcfConnectStatus", 0, _trace_param_, "");
            }

            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"getMgcfConnectStatus", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Bool _ret = false;
            _is.read(_ret, 0, true);
            _is.read(mgcfSipGatewayOid, 2, true);
            _is.read(params, 3, true);
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CR, _is.size());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                    _p_->value["mgcfSipGatewayOid"] = tars::JsonOutput::writeJson(mgcfSipGatewayOid);
                    _p_->value["params"] = tars::JsonOutput::writeJson(params);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CR), TRACE_ANNOTATION_CR, tars_moduleName(), tars_name(), "getMgcfConnectStatus", 0, _trace_param_, "");
            }

            return _ret;
        }

        void async_getMgcfConnectStatus(SipRelayPrxCallbackPtr callback,const std::string &sipGatewayId,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(sipGatewayId, 1);
            std::map<string, string> _mStatus;
            ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                _pSptd_->newSpan();
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CS, _os.getLength());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value["sipGatewayId"] = tars::JsonOutput::writeJson(sipGatewayId);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CS), TRACE_ANNOTATION_CS, tars_moduleName(), tars_name(), "getMgcfConnectStatus", 0, _trace_param_, "");
            }
            tars_invoke_async(tars::TARSNORMAL,"getMgcfConnectStatus", _os, context, _mStatus, callback);
        }
        
        tars::Future< SipRelayPrxCallbackPromise::PromisegetMgcfConnectStatusPtr > promise_async_getMgcfConnectStatus(const std::string &sipGatewayId,const map<string, string>& context)
        {
            tars::Promise< SipRelayPrxCallbackPromise::PromisegetMgcfConnectStatusPtr > promise;
            SipRelayPrxCallbackPromisePtr callback (new SipRelayPrxCallbackPromise(promise));

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(sipGatewayId, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"getMgcfConnectStatus", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_getMgcfConnectStatus(SipRelayCoroPrxCallbackPtr callback,const std::string &sipGatewayId,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(sipGatewayId, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"getMgcfConnectStatus", _os, context, _mStatus, callback, true);
        }

        tars::Bool recvSipMsgFromCloudSipGateway(const std::string & sipGatewayId,const std::string & sipMsg,const std::string & connectionId,const map<std::string, std::string> & params,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(sipGatewayId, 1);
            _os.write(sipMsg, 2);
            _os.write(connectionId, 3);
            _os.write(params, 4);
            ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                _pSptd_->newSpan();
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CS, _os.getLength());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value["sipGatewayId"] = tars::JsonOutput::writeJson(sipGatewayId);
                    _p_->value["sipMsg"] = tars::JsonOutput::writeJson(sipMsg);
                    _p_->value["connectionId"] = tars::JsonOutput::writeJson(connectionId);
                    _p_->value["params"] = tars::JsonOutput::writeJson(params);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CS), TRACE_ANNOTATION_CS, tars_moduleName(), tars_name(), "recvSipMsgFromCloudSipGateway", 0, _trace_param_, "");
            }

            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"recvSipMsgFromCloudSipGateway", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Bool _ret = false;
            _is.read(_ret, 0, true);
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CR, _is.size());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CR), TRACE_ANNOTATION_CR, tars_moduleName(), tars_name(), "recvSipMsgFromCloudSipGateway", 0, _trace_param_, "");
            }

            return _ret;
        }

        void async_recvSipMsgFromCloudSipGateway(SipRelayPrxCallbackPtr callback,const std::string &sipGatewayId,const std::string &sipMsg,const std::string &connectionId,const map<std::string, std::string> &params,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(sipGatewayId, 1);
            _os.write(sipMsg, 2);
            _os.write(connectionId, 3);
            _os.write(params, 4);
            std::map<string, string> _mStatus;
            ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                _pSptd_->newSpan();
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CS, _os.getLength());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value["sipGatewayId"] = tars::JsonOutput::writeJson(sipGatewayId);
                    _p_->value["sipMsg"] = tars::JsonOutput::writeJson(sipMsg);
                    _p_->value["connectionId"] = tars::JsonOutput::writeJson(connectionId);
                    _p_->value["params"] = tars::JsonOutput::writeJson(params);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CS), TRACE_ANNOTATION_CS, tars_moduleName(), tars_name(), "recvSipMsgFromCloudSipGateway", 0, _trace_param_, "");
            }
            tars_invoke_async(tars::TARSNORMAL,"recvSipMsgFromCloudSipGateway", _os, context, _mStatus, callback);
        }
        
        tars::Future< SipRelayPrxCallbackPromise::PromiserecvSipMsgFromCloudSipGatewayPtr > promise_async_recvSipMsgFromCloudSipGateway(const std::string &sipGatewayId,const std::string &sipMsg,const std::string &connectionId,const map<std::string, std::string> &params,const map<string, string>& context)
        {
            tars::Promise< SipRelayPrxCallbackPromise::PromiserecvSipMsgFromCloudSipGatewayPtr > promise;
            SipRelayPrxCallbackPromisePtr callback (new SipRelayPrxCallbackPromise(promise));

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(sipGatewayId, 1);
            _os.write(sipMsg, 2);
            _os.write(connectionId, 3);
            _os.write(params, 4);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"recvSipMsgFromCloudSipGateway", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_recvSipMsgFromCloudSipGateway(SipRelayCoroPrxCallbackPtr callback,const std::string &sipGatewayId,const std::string &sipMsg,const std::string &connectionId,const map<std::string, std::string> &params,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(sipGatewayId, 1);
            _os.write(sipMsg, 2);
            _os.write(connectionId, 3);
            _os.write(params, 4);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"recvSipMsgFromCloudSipGateway", _os, context, _mStatus, callback, true);
        }

        SipRelayProxy* tars_hash(size_t key)
        {
            return (SipRelayProxy*)ServantProxy::tars_hash(key);
        }

        SipRelayProxy* tars_consistent_hash(size_t key)
        {
            return (SipRelayProxy*)ServantProxy::tars_consistent_hash(key);
        }

        SipRelayProxy* tars_open_trace(bool traceParam = false)
        {
            return (SipRelayProxy*)ServantProxy::tars_open_trace(traceParam);
        }

        SipRelayProxy* tars_set_timeout(int msecond)
        {
            return (SipRelayProxy*)ServantProxy::tars_set_timeout(msecond);
        }

        static const char* tars_prxname() { return "SipRelayProxy"; }
    };
    typedef tars::TC_AutoPtr<SipRelayProxy> SipRelayPrx;

    /* servant for server */
    class SipRelay : public tars::Servant
    {
    public:
        virtual ~SipRelay(){}
        virtual tars::Bool eraseSipDlgIdAndConnection(const std::string & sipGatewayId,const std::string & dialogId,tars::TarsCurrentPtr _current_) = 0;
        virtual tars::Bool eraseSipDlgIdAndConnection(std::string && sipGatewayId,std::string && dialogId,tars::TarsCurrentPtr _current_) 
        { return eraseSipDlgIdAndConnection(sipGatewayId, dialogId, _current_); }
        static void async_response_eraseSipDlgIdAndConnection(tars::TarsCurrentPtr _current_, tars::Bool _ret)
        {
            size_t _rsp_len_ = 0;
            if (_current_->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                _tarsAttr_.setVersion(_current_->getRequestVersion());
                _tarsAttr_.put("", _ret);
                _tarsAttr_.put("tars_ret", _ret);

                vector<char> sTupResponseBuffer;
                _tarsAttr_.encode(sTupResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, _tarsAttr_);
                _rsp_len_ = sTupResponseBuffer.size();
            }
            else if (_current_->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
                _rsp_len_ = sJsonResponseBuffer.size();
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _rsp_len_ = _os.getLength();
                _current_->sendResponse(tars::TARSSERVERSUCCESS, _os);
            }
            if (_current_->isTraced())
            {
                string _trace_param_;
                int _trace_param_flag_ = ServantProxyThreadData::needTraceParam(ServantProxyThreadData::TraceContext::EST_SS, _current_->getTraceKey(), _rsp_len_);
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                if(_current_->getServantHandle())
                {
                    TARS_TRACE(_current_->getTraceKey(), TRACE_ANNOTATION_SS, "", _current_->getModuleName(), "eraseSipDlgIdAndConnection", 0, _trace_param_, "");
                }
            }

        }
        static void async_response_push_eraseSipDlgIdAndConnection(tars::CurrentPtr _current_, tars::Bool _ret, const map<string, string> &_context = tars::Current::TARS_STATUS())
        {
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _current_->sendPushResponse( tars::TARSSERVERSUCCESS ,"eraseSipDlgIdAndConnection", _os, _context);
            }
        }

        virtual tars::Bool getIntranetIp(const std::string & sipGatewayId,std::string &mgcfSipGatewayOid,std::string &intranetIp,tars::TarsCurrentPtr _current_) = 0;
        virtual tars::Bool getIntranetIp(std::string && sipGatewayId,std::string &mgcfSipGatewayOid,std::string &intranetIp,tars::TarsCurrentPtr _current_) 
        { return getIntranetIp(sipGatewayId, mgcfSipGatewayOid, intranetIp, _current_); }
        static void async_response_getIntranetIp(tars::TarsCurrentPtr _current_, tars::Bool _ret, const std::string &mgcfSipGatewayOid, const std::string &intranetIp)
        {
            size_t _rsp_len_ = 0;
            if (_current_->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                _tarsAttr_.setVersion(_current_->getRequestVersion());
                _tarsAttr_.put("", _ret);
                _tarsAttr_.put("tars_ret", _ret);
                _tarsAttr_.put("mgcfSipGatewayOid", mgcfSipGatewayOid);
                _tarsAttr_.put("intranetIp", intranetIp);

                vector<char> sTupResponseBuffer;
                _tarsAttr_.encode(sTupResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, _tarsAttr_);
                _rsp_len_ = sTupResponseBuffer.size();
            }
            else if (_current_->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["mgcfSipGatewayOid"] = tars::JsonOutput::writeJson(mgcfSipGatewayOid);
                _p->value["intranetIp"] = tars::JsonOutput::writeJson(intranetIp);
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
                _rsp_len_ = sJsonResponseBuffer.size();
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(mgcfSipGatewayOid, 2);

                _os.write(intranetIp, 3);

                _rsp_len_ = _os.getLength();
                _current_->sendResponse(tars::TARSSERVERSUCCESS, _os);
            }
            if (_current_->isTraced())
            {
                string _trace_param_;
                int _trace_param_flag_ = ServantProxyThreadData::needTraceParam(ServantProxyThreadData::TraceContext::EST_SS, _current_->getTraceKey(), _rsp_len_);
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                    _p_->value["mgcfSipGatewayOid"] = tars::JsonOutput::writeJson(mgcfSipGatewayOid);
                    _p_->value["intranetIp"] = tars::JsonOutput::writeJson(intranetIp);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                if(_current_->getServantHandle())
                {
                    TARS_TRACE(_current_->getTraceKey(), TRACE_ANNOTATION_SS, "", _current_->getModuleName(), "getIntranetIp", 0, _trace_param_, "");
                }
            }

        }
        static void async_response_push_getIntranetIp(tars::CurrentPtr _current_, tars::Bool _ret, const std::string &mgcfSipGatewayOid, const std::string &intranetIp, const map<string, string> &_context = tars::Current::TARS_STATUS())
        {
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(mgcfSipGatewayOid, 2);

                _os.write(intranetIp, 3);

                _current_->sendPushResponse( tars::TARSSERVERSUCCESS ,"getIntranetIp", _os, _context);
            }
        }

        virtual tars::Bool getMgcfConnectStatus(const std::string & sipGatewayId,std::string &mgcfSipGatewayOid,map<std::string, std::string> &params,tars::TarsCurrentPtr _current_) = 0;
        virtual tars::Bool getMgcfConnectStatus(std::string && sipGatewayId,std::string &mgcfSipGatewayOid,map<std::string, std::string> &params,tars::TarsCurrentPtr _current_) 
        { return getMgcfConnectStatus(sipGatewayId, mgcfSipGatewayOid, params, _current_); }
        static void async_response_getMgcfConnectStatus(tars::TarsCurrentPtr _current_, tars::Bool _ret, const std::string &mgcfSipGatewayOid, const map<std::string, std::string> &params)
        {
            size_t _rsp_len_ = 0;
            if (_current_->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                _tarsAttr_.setVersion(_current_->getRequestVersion());
                _tarsAttr_.put("", _ret);
                _tarsAttr_.put("tars_ret", _ret);
                _tarsAttr_.put("mgcfSipGatewayOid", mgcfSipGatewayOid);
                _tarsAttr_.put("params", params);

                vector<char> sTupResponseBuffer;
                _tarsAttr_.encode(sTupResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, _tarsAttr_);
                _rsp_len_ = sTupResponseBuffer.size();
            }
            else if (_current_->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["mgcfSipGatewayOid"] = tars::JsonOutput::writeJson(mgcfSipGatewayOid);
                _p->value["params"] = tars::JsonOutput::writeJson(params);
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
                _rsp_len_ = sJsonResponseBuffer.size();
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(mgcfSipGatewayOid, 2);

                _os.write(params, 3);

                _rsp_len_ = _os.getLength();
                _current_->sendResponse(tars::TARSSERVERSUCCESS, _os);
            }
            if (_current_->isTraced())
            {
                string _trace_param_;
                int _trace_param_flag_ = ServantProxyThreadData::needTraceParam(ServantProxyThreadData::TraceContext::EST_SS, _current_->getTraceKey(), _rsp_len_);
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                    _p_->value["mgcfSipGatewayOid"] = tars::JsonOutput::writeJson(mgcfSipGatewayOid);
                    _p_->value["params"] = tars::JsonOutput::writeJson(params);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                if(_current_->getServantHandle())
                {
                    TARS_TRACE(_current_->getTraceKey(), TRACE_ANNOTATION_SS, "", _current_->getModuleName(), "getMgcfConnectStatus", 0, _trace_param_, "");
                }
            }

        }
        static void async_response_push_getMgcfConnectStatus(tars::CurrentPtr _current_, tars::Bool _ret, const std::string &mgcfSipGatewayOid, const map<std::string, std::string> &params, const map<string, string> &_context = tars::Current::TARS_STATUS())
        {
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(mgcfSipGatewayOid, 2);

                _os.write(params, 3);

                _current_->sendPushResponse( tars::TARSSERVERSUCCESS ,"getMgcfConnectStatus", _os, _context);
            }
        }

        virtual tars::Bool recvSipMsgFromCloudSipGateway(const std::string & sipGatewayId,const std::string & sipMsg,const std::string & connectionId,const map<std::string, std::string> & params,tars::TarsCurrentPtr _current_) = 0;
        virtual tars::Bool recvSipMsgFromCloudSipGateway(std::string && sipGatewayId,std::string && sipMsg,std::string && connectionId,map<std::string, std::string> && params,tars::TarsCurrentPtr _current_) 
        { return recvSipMsgFromCloudSipGateway(sipGatewayId, sipMsg, connectionId, params, _current_); }
        static void async_response_recvSipMsgFromCloudSipGateway(tars::TarsCurrentPtr _current_, tars::Bool _ret)
        {
            size_t _rsp_len_ = 0;
            if (_current_->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                _tarsAttr_.setVersion(_current_->getRequestVersion());
                _tarsAttr_.put("", _ret);
                _tarsAttr_.put("tars_ret", _ret);

                vector<char> sTupResponseBuffer;
                _tarsAttr_.encode(sTupResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, _tarsAttr_);
                _rsp_len_ = sTupResponseBuffer.size();
            }
            else if (_current_->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
                _rsp_len_ = sJsonResponseBuffer.size();
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _rsp_len_ = _os.getLength();
                _current_->sendResponse(tars::TARSSERVERSUCCESS, _os);
            }
            if (_current_->isTraced())
            {
                string _trace_param_;
                int _trace_param_flag_ = ServantProxyThreadData::needTraceParam(ServantProxyThreadData::TraceContext::EST_SS, _current_->getTraceKey(), _rsp_len_);
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                if(_current_->getServantHandle())
                {
                    TARS_TRACE(_current_->getTraceKey(), TRACE_ANNOTATION_SS, "", _current_->getModuleName(), "recvSipMsgFromCloudSipGateway", 0, _trace_param_, "");
                }
            }

        }
        static void async_response_push_recvSipMsgFromCloudSipGateway(tars::CurrentPtr _current_, tars::Bool _ret, const map<string, string> &_context = tars::Current::TARS_STATUS())
        {
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _current_->sendPushResponse( tars::TARSSERVERSUCCESS ,"recvSipMsgFromCloudSipGateway", _os, _context);
            }
        }

    public:
        int onDispatch(tars::TarsCurrentPtr _current, vector<char> &_sResponseBuffer)
        {
            static ::std::string __VoipApp__SipRelay_all[]=
            {
                "eraseSipDlgIdAndConnection",
                "getIntranetIp",
                "getMgcfConnectStatus",
                "recvSipMsgFromCloudSipGateway"
            };

            pair<string*, string*> r = equal_range(__VoipApp__SipRelay_all, __VoipApp__SipRelay_all+4, _current->getFuncName());
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __VoipApp__SipRelay_all)
            {
                case 0:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string sipGatewayId;
                    std::string dialogId;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                        _tarsAttr_.setVersion(_current->getRequestVersion());
                        _tarsAttr_.decode(_current->getRequestBuffer());
                        _tarsAttr_.get("sipGatewayId", sipGatewayId);
                        _tarsAttr_.get("dialogId", dialogId);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(sipGatewayId, _jsonPtr->value["sipGatewayId"], true);
                        tars::JsonInput::readJson(dialogId, _jsonPtr->value["dialogId"], true);
                    }
                    else
                    {
                        _is.read(sipGatewayId, 1, true);
                        _is.read(dialogId, 2, true);
                    }
                    ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
                    if (_pSptd_ && _pSptd_->_traceCall)
                    {
                        string _trace_param_;
                        int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_SR, _is.size());
                        if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                        {
                            tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                            _p_->value["sipGatewayId"] = tars::JsonOutput::writeJson(sipGatewayId);
                            _p_->value["dialogId"] = tars::JsonOutput::writeJson(dialogId);
                            _trace_param_ = tars::TC_Json::writeValue(_p_);
                        }
                        else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                        {
                            _trace_param_ = "{\"trace_param_over_max_len\":true}";
                        }
                        TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SR), TRACE_ANNOTATION_SR, "", getModuleName(), "eraseSipDlgIdAndConnection", 0, _trace_param_, "");
                    }

                    tars::Bool _ret = eraseSipDlgIdAndConnection(std::move(sipGatewayId),std::move(dialogId), _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                            _tarsAttr_.setVersion(_current->getRequestVersion());
                            _tarsAttr_.put("", _ret);
                            _tarsAttr_.put("tars_ret", _ret);
                            _tarsAttr_.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.swap(_sResponseBuffer);
                        }
                        if (_pSptd_ && _pSptd_->_traceCall)
                        {
                            string _trace_param_;
                            int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_SS, _sResponseBuffer.size());
                            if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                            {
                                tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                                _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                                _trace_param_ = tars::TC_Json::writeValue(_p_);
                            }
                            else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                            {
                                _trace_param_ = "{\"trace_param_over_max_len\":true}";
                            }
                            TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SS), TRACE_ANNOTATION_SS, "", getModuleName(), "eraseSipDlgIdAndConnection", 0, _trace_param_, "");
                        }

                    }
                    else if(_pSptd_ && _pSptd_->_traceCall)
                    {
                        _current->setTrace(_pSptd_->_traceCall, _pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SS));
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string sipGatewayId;
                    std::string mgcfSipGatewayOid;
                    std::string intranetIp;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                        _tarsAttr_.setVersion(_current->getRequestVersion());
                        _tarsAttr_.decode(_current->getRequestBuffer());
                        _tarsAttr_.get("sipGatewayId", sipGatewayId);
                        _tarsAttr_.getByDefault("mgcfSipGatewayOid", mgcfSipGatewayOid, mgcfSipGatewayOid);
                        _tarsAttr_.getByDefault("intranetIp", intranetIp, intranetIp);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(sipGatewayId, _jsonPtr->value["sipGatewayId"], true);
                        tars::JsonInput::readJson(mgcfSipGatewayOid, _jsonPtr->value["mgcfSipGatewayOid"], false);
                        tars::JsonInput::readJson(intranetIp, _jsonPtr->value["intranetIp"], false);
                    }
                    else
                    {
                        _is.read(sipGatewayId, 1, true);
                        _is.read(mgcfSipGatewayOid, 2, false);
                        _is.read(intranetIp, 3, false);
                    }
                    ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
                    if (_pSptd_ && _pSptd_->_traceCall)
                    {
                        string _trace_param_;
                        int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_SR, _is.size());
                        if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                        {
                            tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                            _p_->value["sipGatewayId"] = tars::JsonOutput::writeJson(sipGatewayId);
                            _trace_param_ = tars::TC_Json::writeValue(_p_);
                        }
                        else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                        {
                            _trace_param_ = "{\"trace_param_over_max_len\":true}";
                        }
                        TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SR), TRACE_ANNOTATION_SR, "", getModuleName(), "getIntranetIp", 0, _trace_param_, "");
                    }

                    tars::Bool _ret = getIntranetIp(std::move(sipGatewayId),mgcfSipGatewayOid,intranetIp, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                            _tarsAttr_.setVersion(_current->getRequestVersion());
                            _tarsAttr_.put("", _ret);
                            _tarsAttr_.put("tars_ret", _ret);
                            _tarsAttr_.put("mgcfSipGatewayOid", mgcfSipGatewayOid);
                            _tarsAttr_.put("intranetIp", intranetIp);
                            _tarsAttr_.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["mgcfSipGatewayOid"] = tars::JsonOutput::writeJson(mgcfSipGatewayOid);
                            _p->value["intranetIp"] = tars::JsonOutput::writeJson(intranetIp);
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.write(mgcfSipGatewayOid, 2);
                            _os.write(intranetIp, 3);
                            _os.swap(_sResponseBuffer);
                        }
                        if (_pSptd_ && _pSptd_->_traceCall)
                        {
                            string _trace_param_;
                            int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_SS, _sResponseBuffer.size());
                            if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                            {
                                tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                                _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                                _p_->value["mgcfSipGatewayOid"] = tars::JsonOutput::writeJson(mgcfSipGatewayOid);
                                _p_->value["intranetIp"] = tars::JsonOutput::writeJson(intranetIp);
                                _trace_param_ = tars::TC_Json::writeValue(_p_);
                            }
                            else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                            {
                                _trace_param_ = "{\"trace_param_over_max_len\":true}";
                            }
                            TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SS), TRACE_ANNOTATION_SS, "", getModuleName(), "getIntranetIp", 0, _trace_param_, "");
                        }

                    }
                    else if(_pSptd_ && _pSptd_->_traceCall)
                    {
                        _current->setTrace(_pSptd_->_traceCall, _pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SS));
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string sipGatewayId;
                    std::string mgcfSipGatewayOid;
                    map<std::string, std::string> params;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                        _tarsAttr_.setVersion(_current->getRequestVersion());
                        _tarsAttr_.decode(_current->getRequestBuffer());
                        _tarsAttr_.get("sipGatewayId", sipGatewayId);
                        _tarsAttr_.getByDefault("mgcfSipGatewayOid", mgcfSipGatewayOid, mgcfSipGatewayOid);
                        _tarsAttr_.getByDefault("params", params, params);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(sipGatewayId, _jsonPtr->value["sipGatewayId"], true);
                        tars::JsonInput::readJson(mgcfSipGatewayOid, _jsonPtr->value["mgcfSipGatewayOid"], false);
                        tars::JsonInput::readJson(params, _jsonPtr->value["params"], false);
                    }
                    else
                    {
                        _is.read(sipGatewayId, 1, true);
                        _is.read(mgcfSipGatewayOid, 2, false);
                        _is.read(params, 3, false);
                    }
                    ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
                    if (_pSptd_ && _pSptd_->_traceCall)
                    {
                        string _trace_param_;
                        int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_SR, _is.size());
                        if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                        {
                            tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                            _p_->value["sipGatewayId"] = tars::JsonOutput::writeJson(sipGatewayId);
                            _trace_param_ = tars::TC_Json::writeValue(_p_);
                        }
                        else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                        {
                            _trace_param_ = "{\"trace_param_over_max_len\":true}";
                        }
                        TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SR), TRACE_ANNOTATION_SR, "", getModuleName(), "getMgcfConnectStatus", 0, _trace_param_, "");
                    }

                    tars::Bool _ret = getMgcfConnectStatus(std::move(sipGatewayId),mgcfSipGatewayOid,params, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                            _tarsAttr_.setVersion(_current->getRequestVersion());
                            _tarsAttr_.put("", _ret);
                            _tarsAttr_.put("tars_ret", _ret);
                            _tarsAttr_.put("mgcfSipGatewayOid", mgcfSipGatewayOid);
                            _tarsAttr_.put("params", params);
                            _tarsAttr_.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["mgcfSipGatewayOid"] = tars::JsonOutput::writeJson(mgcfSipGatewayOid);
                            _p->value["params"] = tars::JsonOutput::writeJson(params);
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.write(mgcfSipGatewayOid, 2);
                            _os.write(params, 3);
                            _os.swap(_sResponseBuffer);
                        }
                        if (_pSptd_ && _pSptd_->_traceCall)
                        {
                            string _trace_param_;
                            int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_SS, _sResponseBuffer.size());
                            if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                            {
                                tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                                _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                                _p_->value["mgcfSipGatewayOid"] = tars::JsonOutput::writeJson(mgcfSipGatewayOid);
                                _p_->value["params"] = tars::JsonOutput::writeJson(params);
                                _trace_param_ = tars::TC_Json::writeValue(_p_);
                            }
                            else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                            {
                                _trace_param_ = "{\"trace_param_over_max_len\":true}";
                            }
                            TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SS), TRACE_ANNOTATION_SS, "", getModuleName(), "getMgcfConnectStatus", 0, _trace_param_, "");
                        }

                    }
                    else if(_pSptd_ && _pSptd_->_traceCall)
                    {
                        _current->setTrace(_pSptd_->_traceCall, _pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SS));
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string sipGatewayId;
                    std::string sipMsg;
                    std::string connectionId;
                    map<std::string, std::string> params;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                        _tarsAttr_.setVersion(_current->getRequestVersion());
                        _tarsAttr_.decode(_current->getRequestBuffer());
                        _tarsAttr_.get("sipGatewayId", sipGatewayId);
                        _tarsAttr_.get("sipMsg", sipMsg);
                        _tarsAttr_.get("connectionId", connectionId);
                        _tarsAttr_.get("params", params);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(sipGatewayId, _jsonPtr->value["sipGatewayId"], true);
                        tars::JsonInput::readJson(sipMsg, _jsonPtr->value["sipMsg"], true);
                        tars::JsonInput::readJson(connectionId, _jsonPtr->value["connectionId"], true);
                        tars::JsonInput::readJson(params, _jsonPtr->value["params"], true);
                    }
                    else
                    {
                        _is.read(sipGatewayId, 1, true);
                        _is.read(sipMsg, 2, true);
                        _is.read(connectionId, 3, true);
                        _is.read(params, 4, true);
                    }
                    ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
                    if (_pSptd_ && _pSptd_->_traceCall)
                    {
                        string _trace_param_;
                        int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_SR, _is.size());
                        if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                        {
                            tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                            _p_->value["sipGatewayId"] = tars::JsonOutput::writeJson(sipGatewayId);
                            _p_->value["sipMsg"] = tars::JsonOutput::writeJson(sipMsg);
                            _p_->value["connectionId"] = tars::JsonOutput::writeJson(connectionId);
                            _p_->value["params"] = tars::JsonOutput::writeJson(params);
                            _trace_param_ = tars::TC_Json::writeValue(_p_);
                        }
                        else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                        {
                            _trace_param_ = "{\"trace_param_over_max_len\":true}";
                        }
                        TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SR), TRACE_ANNOTATION_SR, "", getModuleName(), "recvSipMsgFromCloudSipGateway", 0, _trace_param_, "");
                    }

                    tars::Bool _ret = recvSipMsgFromCloudSipGateway(std::move(sipGatewayId),std::move(sipMsg),std::move(connectionId),std::move(params), _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                            _tarsAttr_.setVersion(_current->getRequestVersion());
                            _tarsAttr_.put("", _ret);
                            _tarsAttr_.put("tars_ret", _ret);
                            _tarsAttr_.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.swap(_sResponseBuffer);
                        }
                        if (_pSptd_ && _pSptd_->_traceCall)
                        {
                            string _trace_param_;
                            int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_SS, _sResponseBuffer.size());
                            if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                            {
                                tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                                _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                                _trace_param_ = tars::TC_Json::writeValue(_p_);
                            }
                            else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                            {
                                _trace_param_ = "{\"trace_param_over_max_len\":true}";
                            }
                            TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SS), TRACE_ANNOTATION_SS, "", getModuleName(), "recvSipMsgFromCloudSipGateway", 0, _trace_param_, "");
                        }

                    }
                    else if(_pSptd_ && _pSptd_->_traceCall)
                    {
                        _current->setTrace(_pSptd_->_traceCall, _pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SS));
                    }

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }
    };


}



#endif
