#ifndef _GENERAL_DESIGN_MEDIA_FLOW_C_TYPE_H_
#define _GENERAL_DESIGN_MEDIA_FLOW_C_TYPE_H_

//#include "stdio.h"
//#include "string.h"

enum MEDIA_CODEC_ID {
    MEDIA_CODEC_ID_NONE,

    /* video codecs */
    MEDIA_CODEC_ID_MPEG1VIDEO,
    MEDIA_CODEC_ID_MPEG2VIDEO, ///< preferred ID for MPEG-1/2 video decoding
    MEDIA_CODEC_ID_H261,
    MEDIA_CODEC_ID_H263,
    MEDIA_CODEC_ID_RV10,
    MEDIA_CODEC_ID_RV20,
    MEDIA_CODEC_ID_MJPEG,
    MEDIA_CODEC_ID_MJPEGB,
    MEDIA_CODEC_ID_LJPEG,
    MEDIA_CODEC_ID_SP5X,
    MEDIA_CODEC_ID_JPEGLS,
    MEDIA_CODEC_ID_MPEG4,
    MEDIA_CODEC_ID_RAWVIDEO,
    MEDIA_CODEC_ID_MSMPEG4V1,
    MEDIA_CODEC_ID_MSMPEG4V2,
    MEDIA_CODEC_ID_MSMPEG4V3,
    MEDIA_CODEC_ID_WMV1,
    MEDIA_CODEC_ID_WMV2,
    MEDIA_CODEC_ID_H263P,
    MEDIA_CODEC_ID_H263I,
    MEDIA_CODEC_ID_FLV1,
    MEDIA_CODEC_ID_SVQ1,
    MEDIA_CODEC_ID_SVQ3,
    MEDIA_CODEC_ID_DVVIDEO,
    MEDIA_CODEC_ID_HUFFYUV,
    MEDIA_CODEC_ID_CYUV,
    MEDIA_CODEC_ID_H264,
    MEDIA_CODEC_ID_INDEO3,
    MEDIA_CODEC_ID_VP3,
    MEDIA_CODEC_ID_THEORA,
    MEDIA_CODEC_ID_ASV1,
    MEDIA_CODEC_ID_ASV2,
    MEDIA_CODEC_ID_FFV1,
    MEDIA_CODEC_ID_4XM,
    MEDIA_CODEC_ID_VCR1,
    MEDIA_CODEC_ID_CLJR,
    MEDIA_CODEC_ID_MDEC,
    MEDIA_CODEC_ID_ROQ,
    MEDIA_CODEC_ID_INTERPLAY_VIDEO,
    MEDIA_CODEC_ID_XAN_WC3,
    MEDIA_CODEC_ID_XAN_WC4,
    MEDIA_CODEC_ID_RPZA,
    MEDIA_CODEC_ID_CINEPAK,
    MEDIA_CODEC_ID_WS_VQA,
    MEDIA_CODEC_ID_MSRLE,
    MEDIA_CODEC_ID_MSVIDEO1,
    MEDIA_CODEC_ID_IDCIN,
    MEDIA_CODEC_ID_8BPS,
    MEDIA_CODEC_ID_SMC,
    MEDIA_CODEC_ID_FLIC,
    MEDIA_CODEC_ID_TRUEMOTION1,
    MEDIA_CODEC_ID_VMDVIDEO,
    MEDIA_CODEC_ID_MSZH,
    MEDIA_CODEC_ID_ZLIB,
    MEDIA_CODEC_ID_QTRLE,
    MEDIA_CODEC_ID_TSCC,
    MEDIA_CODEC_ID_ULTI,
    MEDIA_CODEC_ID_QDRAW,
    MEDIA_CODEC_ID_VIXL,
    MEDIA_CODEC_ID_QPEG,
    MEDIA_CODEC_ID_PNG,
    MEDIA_CODEC_ID_PPM,
    MEDIA_CODEC_ID_PBM,
    MEDIA_CODEC_ID_PGM,
    MEDIA_CODEC_ID_PGMYUV,
    MEDIA_CODEC_ID_PAM,
    MEDIA_CODEC_ID_FFVHUFF,
    MEDIA_CODEC_ID_RV30,
    MEDIA_CODEC_ID_RV40,
    MEDIA_CODEC_ID_VC1,
    MEDIA_CODEC_ID_WMV3,
    MEDIA_CODEC_ID_LOCO,
    MEDIA_CODEC_ID_WNV1,
    MEDIA_CODEC_ID_AASC,
    MEDIA_CODEC_ID_INDEO2,
    MEDIA_CODEC_ID_FRAPS,
    MEDIA_CODEC_ID_TRUEMOTION2,
    MEDIA_CODEC_ID_BMP,
    MEDIA_CODEC_ID_CSCD,
    MEDIA_CODEC_ID_MMVIDEO,
    MEDIA_CODEC_ID_ZMBV,
    MEDIA_CODEC_ID_AVS,
    MEDIA_CODEC_ID_SMACKVIDEO,
    MEDIA_CODEC_ID_NUV,
    MEDIA_CODEC_ID_KMVC,
    MEDIA_CODEC_ID_FLASHSV,
    MEDIA_CODEC_ID_CAVS,
    MEDIA_CODEC_ID_JPEG2000,
    MEDIA_CODEC_ID_VMNC,
    MEDIA_CODEC_ID_VP5,
    MEDIA_CODEC_ID_VP6,
    MEDIA_CODEC_ID_VP6F,
    MEDIA_CODEC_ID_TARGA,
    MEDIA_CODEC_ID_DSICINVIDEO,
    MEDIA_CODEC_ID_TIERTEXSEQVIDEO,
    MEDIA_CODEC_ID_TIFF,
    MEDIA_CODEC_ID_GIF,
    MEDIA_CODEC_ID_DXA,
    MEDIA_CODEC_ID_DNXHD,
    MEDIA_CODEC_ID_THP,
    MEDIA_CODEC_ID_SGI,
    MEDIA_CODEC_ID_C93,
    MEDIA_CODEC_ID_BETHSOFTVID,
    MEDIA_CODEC_ID_PTX,
    MEDIA_CODEC_ID_TXD,
    MEDIA_CODEC_ID_VP6A,
    MEDIA_CODEC_ID_AMV,
    MEDIA_CODEC_ID_VB,
    MEDIA_CODEC_ID_PCX,
    MEDIA_CODEC_ID_SUNRAST,
    MEDIA_CODEC_ID_INDEO4,
    MEDIA_CODEC_ID_INDEO5,
    MEDIA_CODEC_ID_MIMIC,
    MEDIA_CODEC_ID_RL2,
    MEDIA_CODEC_ID_ESCAPE124,
    MEDIA_CODEC_ID_DIRAC,
    MEDIA_CODEC_ID_BFI,
    MEDIA_CODEC_ID_CMV,
    MEDIA_CODEC_ID_MOTIONPIXELS,
    MEDIA_CODEC_ID_TGV,
    MEDIA_CODEC_ID_TGQ,
    MEDIA_CODEC_ID_TQI,
    MEDIA_CODEC_ID_AURA,
    MEDIA_CODEC_ID_AURA2,
    MEDIA_CODEC_ID_V210X,
    MEDIA_CODEC_ID_TMV,
    MEDIA_CODEC_ID_V210,
    MEDIA_CODEC_ID_DPX,
    MEDIA_CODEC_ID_MAD,
    MEDIA_CODEC_ID_FRWU,
    MEDIA_CODEC_ID_FLASHSV2,
    MEDIA_CODEC_ID_CDGRAPHICS,
    MEDIA_CODEC_ID_R210,
    MEDIA_CODEC_ID_ANM,
    MEDIA_CODEC_ID_BINKVIDEO,
    MEDIA_CODEC_ID_IFF_ILBM,
    MEDIA_CODEC_ID_KGV1,
    MEDIA_CODEC_ID_YOP,
    MEDIA_CODEC_ID_VP8,
    MEDIA_CODEC_ID_PICTOR,
    MEDIA_CODEC_ID_ANSI,
    MEDIA_CODEC_ID_A64_MULTI,
    MEDIA_CODEC_ID_A64_MULTI5,
    MEDIA_CODEC_ID_R10K,
    MEDIA_CODEC_ID_MXPEG,
    MEDIA_CODEC_ID_LAGARITH,
    MEDIA_CODEC_ID_PRORES,
    MEDIA_CODEC_ID_JV,
    MEDIA_CODEC_ID_DFA,
    MEDIA_CODEC_ID_WMV3IMAGE,
    MEDIA_CODEC_ID_VC1IMAGE,
    MEDIA_CODEC_ID_UTVIDEO,
    MEDIA_CODEC_ID_BMV_VIDEO,
    MEDIA_CODEC_ID_VBLE,
    MEDIA_CODEC_ID_DXTORY,
    MEDIA_CODEC_ID_V410,
    MEDIA_CODEC_ID_XWD,
    MEDIA_CODEC_ID_CDXL,
    MEDIA_CODEC_ID_XBM,
    MEDIA_CODEC_ID_ZEROCODEC,
    MEDIA_CODEC_ID_MSS1,
    MEDIA_CODEC_ID_MSA1,
    MEDIA_CODEC_ID_TSCC2,
    MEDIA_CODEC_ID_MTS2,
    MEDIA_CODEC_ID_CLLC,
    MEDIA_CODEC_ID_MSS2,
    MEDIA_CODEC_ID_VP9,
    MEDIA_CODEC_ID_AIC,
    MEDIA_CODEC_ID_ESCAPE130,
    MEDIA_CODEC_ID_G2M,
    MEDIA_CODEC_ID_WEBP,
    MEDIA_CODEC_ID_HNM4_VIDEO,
    MEDIA_CODEC_ID_HEVC,
#define MEDIA_CODEC_ID_H265 MEDIA_CODEC_ID_HEVC
    MEDIA_CODEC_ID_FIC,
    MEDIA_CODEC_ID_ALIAS_PIX,
    MEDIA_CODEC_ID_BRENDER_PIX,
    MEDIA_CODEC_ID_PAF_VIDEO,
    MEDIA_CODEC_ID_EXR,
    MEDIA_CODEC_ID_VP7,
    MEDIA_CODEC_ID_SANM,
    MEDIA_CODEC_ID_SGIRLE,
    MEDIA_CODEC_ID_MVC1,
    MEDIA_CODEC_ID_MVC2,
    MEDIA_CODEC_ID_HQX,
    MEDIA_CODEC_ID_TDSC,
    MEDIA_CODEC_ID_HQ_HQA,
    MEDIA_CODEC_ID_HAP,
    MEDIA_CODEC_ID_DDS,
    MEDIA_CODEC_ID_DXV,
    MEDIA_CODEC_ID_SCREENPRESSO,
    MEDIA_CODEC_ID_RSCC,

    MEDIA_CODEC_ID_Y41P = 0x8000,
    MEDIA_CODEC_ID_AVRP,
    MEDIA_CODEC_ID_012V,
    MEDIA_CODEC_ID_AVUI,
    MEDIA_CODEC_ID_AYUV,
    MEDIA_CODEC_ID_TARGA_Y216,
    MEDIA_CODEC_ID_V308,
    MEDIA_CODEC_ID_V408,
    MEDIA_CODEC_ID_YUV4,
    MEDIA_CODEC_ID_AVRN,
    MEDIA_CODEC_ID_CPIA,
    MEDIA_CODEC_ID_XFACE,
    MEDIA_CODEC_ID_SNOW,
    MEDIA_CODEC_ID_SMVJPEG,
    MEDIA_CODEC_ID_APNG,
    MEDIA_CODEC_ID_DAALA,
    MEDIA_CODEC_ID_CFHD,
    MEDIA_CODEC_ID_TRUEMOTION2RT,
    MEDIA_CODEC_ID_M101,
    MEDIA_CODEC_ID_MAGICYUV,
    MEDIA_CODEC_ID_SHEERVIDEO,
    MEDIA_CODEC_ID_YLC,
    MEDIA_CODEC_ID_PSD,
    MEDIA_CODEC_ID_PIXLET,
    MEDIA_CODEC_ID_SPEEDHQ,
    MEDIA_CODEC_ID_FMVC,
    MEDIA_CODEC_ID_SCPR,
    MEDIA_CODEC_ID_CLEARVIDEO,
    MEDIA_CODEC_ID_XPM,
    MEDIA_CODEC_ID_AV1,
    MEDIA_CODEC_ID_BITPACKED,
    MEDIA_CODEC_ID_MSCC,
    MEDIA_CODEC_ID_SRGC,
    MEDIA_CODEC_ID_SVG,
    MEDIA_CODEC_ID_GDV,
    MEDIA_CODEC_ID_FITS,

    /* various PCM "codecs" */
    MEDIA_CODEC_ID_FIRST_AUDIO = 0x10000,     ///< A dummy id pointing at the start of audio codecs
    MEDIA_CODEC_ID_PCM_S16LE = 0x10000,
    MEDIA_CODEC_ID_PCM_S16BE,
    MEDIA_CODEC_ID_PCM_U16LE,
    MEDIA_CODEC_ID_PCM_U16BE,
    MEDIA_CODEC_ID_PCM_S8,
    MEDIA_CODEC_ID_PCM_U8,
    MEDIA_CODEC_ID_PCM_MULAW,
    MEDIA_CODEC_ID_PCM_ALAW,
    MEDIA_CODEC_ID_PCM_S32LE,
    MEDIA_CODEC_ID_PCM_S32BE,
    MEDIA_CODEC_ID_PCM_U32LE,
    MEDIA_CODEC_ID_PCM_U32BE,
    MEDIA_CODEC_ID_PCM_S24LE,
    MEDIA_CODEC_ID_PCM_S24BE,
    MEDIA_CODEC_ID_PCM_U24LE,
    MEDIA_CODEC_ID_PCM_U24BE,
    MEDIA_CODEC_ID_PCM_S24DAUD,
    MEDIA_CODEC_ID_PCM_ZORK,
    MEDIA_CODEC_ID_PCM_S16LE_PLANAR,
    MEDIA_CODEC_ID_PCM_DVD,
    MEDIA_CODEC_ID_PCM_F32BE,
    MEDIA_CODEC_ID_PCM_F32LE,
    MEDIA_CODEC_ID_PCM_F64BE,
    MEDIA_CODEC_ID_PCM_F64LE,
    MEDIA_CODEC_ID_PCM_BLURAY,
    MEDIA_CODEC_ID_PCM_LXF,
    MEDIA_CODEC_ID_S302M,
    MEDIA_CODEC_ID_PCM_S8_PLANAR,
    MEDIA_CODEC_ID_PCM_S24LE_PLANAR,
    MEDIA_CODEC_ID_PCM_S32LE_PLANAR,
    MEDIA_CODEC_ID_PCM_S16BE_PLANAR,

    MEDIA_CODEC_ID_PCM_S64LE = 0x10800,
    MEDIA_CODEC_ID_PCM_S64BE,
    MEDIA_CODEC_ID_PCM_F16LE,
    MEDIA_CODEC_ID_PCM_F24LE,

    /* various ADPCM codecs */
    MEDIA_CODEC_ID_ADPCM_IMA_QT = 0x11000,
    MEDIA_CODEC_ID_ADPCM_IMA_WAV,
    MEDIA_CODEC_ID_ADPCM_IMA_DK3,
    MEDIA_CODEC_ID_ADPCM_IMA_DK4,
    MEDIA_CODEC_ID_ADPCM_IMA_WS,
    MEDIA_CODEC_ID_ADPCM_IMA_SMJPEG,
    MEDIA_CODEC_ID_ADPCM_MS,
    MEDIA_CODEC_ID_ADPCM_4XM,
    MEDIA_CODEC_ID_ADPCM_XA,
    MEDIA_CODEC_ID_ADPCM_ADX,
    MEDIA_CODEC_ID_ADPCM_EA,
    MEDIA_CODEC_ID_ADPCM_G726,
    MEDIA_CODEC_ID_ADPCM_CT,
    MEDIA_CODEC_ID_ADPCM_SWF,
    MEDIA_CODEC_ID_ADPCM_YAMAHA,
    MEDIA_CODEC_ID_ADPCM_SBPRO_4,
    MEDIA_CODEC_ID_ADPCM_SBPRO_3,
    MEDIA_CODEC_ID_ADPCM_SBPRO_2,
    MEDIA_CODEC_ID_ADPCM_THP,
    MEDIA_CODEC_ID_ADPCM_IMA_AMV,
    MEDIA_CODEC_ID_ADPCM_EA_R1,
    MEDIA_CODEC_ID_ADPCM_EA_R3,
    MEDIA_CODEC_ID_ADPCM_EA_R2,
    MEDIA_CODEC_ID_ADPCM_IMA_EA_SEAD,
    MEDIA_CODEC_ID_ADPCM_IMA_EA_EACS,
    MEDIA_CODEC_ID_ADPCM_EA_XAS,
    MEDIA_CODEC_ID_ADPCM_EA_MAXIS_XA,
    MEDIA_CODEC_ID_ADPCM_IMA_ISS,
    MEDIA_CODEC_ID_ADPCM_G722,
    MEDIA_CODEC_ID_ADPCM_IMA_APC,
    MEDIA_CODEC_ID_ADPCM_VIMA,

    MEDIA_CODEC_ID_ADPCM_AFC = 0x11800,
    MEDIA_CODEC_ID_ADPCM_IMA_OKI,
    MEDIA_CODEC_ID_ADPCM_DTK,
    MEDIA_CODEC_ID_ADPCM_IMA_RAD,
    MEDIA_CODEC_ID_ADPCM_G726LE,
    MEDIA_CODEC_ID_ADPCM_THP_LE,
    MEDIA_CODEC_ID_ADPCM_PSX,
    MEDIA_CODEC_ID_ADPCM_AICA,
    MEDIA_CODEC_ID_ADPCM_IMA_DAT4,
    MEDIA_CODEC_ID_ADPCM_MTAF,

    /* AMR */
    MEDIA_CODEC_ID_AMR_NB = 0x12000,
    MEDIA_CODEC_ID_AMR_WB,

    /* RealAudio codecs*/
    MEDIA_CODEC_ID_RA_144 = 0x13000,
    MEDIA_CODEC_ID_RA_288,

    /* various DPCM codecs */
    MEDIA_CODEC_ID_ROQ_DPCM = 0x14000,
    MEDIA_CODEC_ID_INTERPLAY_DPCM,
    MEDIA_CODEC_ID_XAN_DPCM,
    MEDIA_CODEC_ID_SOL_DPCM,

    MEDIA_CODEC_ID_SDX2_DPCM = 0x14800,
    MEDIA_CODEC_ID_GREMLIN_DPCM,

    /* audio codecs */
    MEDIA_CODEC_ID_MP2 = 0x15000,
    MEDIA_CODEC_ID_MP3, ///< preferred ID for decoding MPEG audio layer 1, 2 or 3
    MEDIA_CODEC_ID_AAC,
    MEDIA_CODEC_ID_AC3,
    MEDIA_CODEC_ID_DTS,
    MEDIA_CODEC_ID_VORBIS,
    MEDIA_CODEC_ID_DVAUDIO,
    MEDIA_CODEC_ID_WMAV1,
    MEDIA_CODEC_ID_WMAV2,
    MEDIA_CODEC_ID_MACE3,
    MEDIA_CODEC_ID_MACE6,
    MEDIA_CODEC_ID_VMDAUDIO,
    MEDIA_CODEC_ID_FLAC,
    MEDIA_CODEC_ID_MP3ADU,
    MEDIA_CODEC_ID_MP3ON4,
    MEDIA_CODEC_ID_SHORTEN,
    MEDIA_CODEC_ID_ALAC,
    MEDIA_CODEC_ID_WESTWOOD_SND1,
    MEDIA_CODEC_ID_GSM, ///< as in Berlin toast format
    MEDIA_CODEC_ID_QDM2,
    MEDIA_CODEC_ID_COOK,
    MEDIA_CODEC_ID_TRUESPEECH,
    MEDIA_CODEC_ID_TTA,
    MEDIA_CODEC_ID_SMACKAUDIO,
    MEDIA_CODEC_ID_QCELP,
    MEDIA_CODEC_ID_WAVPACK,
    MEDIA_CODEC_ID_DSICINAUDIO,
    MEDIA_CODEC_ID_IMC,
    MEDIA_CODEC_ID_MUSEPACK7,
    MEDIA_CODEC_ID_MLP,
    MEDIA_CODEC_ID_GSM_MS, /* as found in WAV */
    MEDIA_CODEC_ID_ATRAC3,
    MEDIA_CODEC_ID_APE,
    MEDIA_CODEC_ID_NELLYMOSER,
    MEDIA_CODEC_ID_MUSEPACK8,
    MEDIA_CODEC_ID_SPEEX,
    MEDIA_CODEC_ID_WMAVOICE,
    MEDIA_CODEC_ID_WMAPRO,
    MEDIA_CODEC_ID_WMALOSSLESS,
    MEDIA_CODEC_ID_ATRAC3P,
    MEDIA_CODEC_ID_EAC3,
    MEDIA_CODEC_ID_SIPR,
    MEDIA_CODEC_ID_MP1,
    MEDIA_CODEC_ID_TWINVQ,
    MEDIA_CODEC_ID_TRUEHD,
    MEDIA_CODEC_ID_MP4ALS,
    MEDIA_CODEC_ID_ATRAC1,
    MEDIA_CODEC_ID_BINKAUDIO_RDFT,
    MEDIA_CODEC_ID_BINKAUDIO_DCT,
    MEDIA_CODEC_ID_AAC_LATM,
    MEDIA_CODEC_ID_QDMC,
    MEDIA_CODEC_ID_CELT,
    MEDIA_CODEC_ID_G723_1,
    MEDIA_CODEC_ID_G729,
    MEDIA_CODEC_ID_8SVX_EXP,
    MEDIA_CODEC_ID_8SVX_FIB,
    MEDIA_CODEC_ID_BMV_AUDIO,
    MEDIA_CODEC_ID_RALF,
    MEDIA_CODEC_ID_IAC,
    MEDIA_CODEC_ID_ILBC,
    MEDIA_CODEC_ID_OPUS,
    MEDIA_CODEC_ID_COMFORT_NOISE,
    MEDIA_CODEC_ID_TAK,
    MEDIA_CODEC_ID_METASOUND,
    MEDIA_CODEC_ID_PAF_AUDIO,
    MEDIA_CODEC_ID_ON2AVC,
    MEDIA_CODEC_ID_DSS_SP,
    MEDIA_CODEC_ID_CODEC2,

    MEDIA_CODEC_ID_FFWAVESYNTH = 0x15800,
    MEDIA_CODEC_ID_SONIC,
    MEDIA_CODEC_ID_SONIC_LS,
    MEDIA_CODEC_ID_EVRC,
    MEDIA_CODEC_ID_SMV,
    MEDIA_CODEC_ID_DSD_LSBF,
    MEDIA_CODEC_ID_DSD_MSBF,
    MEDIA_CODEC_ID_DSD_LSBF_PLANAR,
    MEDIA_CODEC_ID_DSD_MSBF_PLANAR,
    MEDIA_CODEC_ID_4GV,
    MEDIA_CODEC_ID_INTERPLAY_ACM,
    MEDIA_CODEC_ID_XMA1,
    MEDIA_CODEC_ID_XMA2,
    MEDIA_CODEC_ID_DST,
    MEDIA_CODEC_ID_ATRAC3AL,
    MEDIA_CODEC_ID_ATRAC3PAL,
    MEDIA_CODEC_ID_DOLBY_E,
    MEDIA_CODEC_ID_APTX,
    MEDIA_CODEC_ID_APTX_HD,
    MEDIA_CODEC_ID_SBC,

    /* subtitle codecs */
    MEDIA_CODEC_ID_FIRST_SUBTITLE = 0x17000,          ///< A dummy ID pointing at the start of subtitle codecs.
    MEDIA_CODEC_ID_DVD_SUBTITLE = 0x17000,
    MEDIA_CODEC_ID_DVB_SUBTITLE,
    MEDIA_CODEC_ID_TEXT,  ///< raw UTF-8 text
    MEDIA_CODEC_ID_XSUB,
    MEDIA_CODEC_ID_SSA,
    MEDIA_CODEC_ID_MOV_TEXT,
    MEDIA_CODEC_ID_HDMV_PGS_SUBTITLE,
    MEDIA_CODEC_ID_DVB_TELETEXT,
    MEDIA_CODEC_ID_SRT,

    MEDIA_CODEC_ID_MICRODVD = 0x17800,
    MEDIA_CODEC_ID_EIA_608,
    MEDIA_CODEC_ID_JACOSUB,
    MEDIA_CODEC_ID_SAMI,
    MEDIA_CODEC_ID_REALTEXT,
    MEDIA_CODEC_ID_STL,
    MEDIA_CODEC_ID_SUBVIEWER1,
    MEDIA_CODEC_ID_SUBVIEWER,
    MEDIA_CODEC_ID_SUBRIP,
    MEDIA_CODEC_ID_WEBVTT,
    MEDIA_CODEC_ID_MPL2,
    MEDIA_CODEC_ID_VPLAYER,
    MEDIA_CODEC_ID_PJS,
    MEDIA_CODEC_ID_ASS,
    MEDIA_CODEC_ID_HDMV_TEXT_SUBTITLE,

    /* other specific kind of codecs (generally used for attachments) */
    MEDIA_CODEC_ID_FIRST_UNKNOWN = 0x18000,           ///< A dummy ID pointing at the start of various fake codecs.
    MEDIA_CODEC_ID_TTF = 0x18000,

    MEDIA_CODEC_ID_SCTE_35, ///< Contain timestamp estimated through PCR of program stream.
    MEDIA_CODEC_ID_BINTEXT = 0x18800,
    MEDIA_CODEC_ID_XBIN,
    MEDIA_CODEC_ID_IDF,
    MEDIA_CODEC_ID_OTF,
    MEDIA_CODEC_ID_SMPTE_KLV,
    MEDIA_CODEC_ID_DVD_NAV,
    MEDIA_CODEC_ID_TIMED_ID3,
    MEDIA_CODEC_ID_BIN_DATA,


    MEDIA_CODEC_ID_PROBE = 0x19000, ///< codec_id is not known (like MEDIA_CODEC_ID_NONE) but lavf should attempt to identify it

    MEDIA_CODEC_ID_MPEG2TS = 0x20000, /**< _FAKE_ codec to indicate a raw MPEG-2 TS
                                      * stream (only used by libavformat) */
    MEDIA_CODEC_ID_MPEG4SYSTEMS = 0x20001, /**< _FAKE_ codec to indicate a MPEG-4 Systems
                                           * stream (only used by libavformat) */
    MEDIA_CODEC_ID_FFMETADATA = 0x21000,   ///< Dummy codec for streams containing only metadata information.
    MEDIA_CODEC_ID_WRAPPED_AVFRAME = 0x21001, ///< Passthrough codec, AVFrames wrapped in AVPacket
};

enum MEDIA_ERROR_CODE {
    /* end of error code */
    ERROR_CODE_UNDEFINED = -500,                /* 未定义的错误 */
    ERROR_CODE_MEMORY_ALLOCATION = -499,        /* 内存分配失败 */
    ERROR_CODE_PARAMETER_ILLEGAL = -498,        /* 参数为NULL、id小于零、列表为空等严重错误 */
    ERROR_CODE_PARAMETER_OUT_OF_RANGE = -497,   /* 参数超出范围 */
    ERROR_CODE_FUNCTION_NOT_SUPPORTED = -496,   /* 功能暂不支持 */
    ERROR_CODE_RESOURCE_EXIST_OR_REPEAT = -495, /* 资源已经存在或者重复：比如重复添加输入源，
                                                                     混音混屏设置布局的时候有重复的id*/
    ERROR_CODE_TARGET_NOT_FOUND = -494,         /* 目标不存在：比如track id列表中有id找不到，
                                                             指定的stream、process等找不到*/

    ERROR_CODE_HAS_OPENED = -480,       /* 已经打开 */
    ERROR_CODE_HAS_CLOSED = -479,       /* 已经关闭 */
    ERROR_CODE_HAS_STARTED = -478,      /* 已经启动 */
    ERROR_CODE_HAS_STOPPED = -477,       /* 已经停止 */
    ERROR_CODE_EOF = -476,              /* 文件或者流结束 */

    /* audio */
    ERROR_CODE_SAMPLERATE_INVALID = -475,  /* 音频采样率不合法 */
    ERROR_CODE_CHANNELS_INVALID = -474,    /* 音频声道数不合法 */

    ERROR_CODE_TRACK_NUMBER = -473,            /* 轨道数量不合法 */
    ERROR_CODE_TRACK_TYPE = -472,              /* 轨道类型不合法，类型指视频、音频 */
    ERROR_CODE_TRACK_FORMAT = -471,            /* 轨道编码格式不合法，编码格式请看MEDIA_CODEC_ID */
    ERROR_CODE_TRACKS_COMBINATION = -470,      /* 轨道组合不合法 */
    ERROR_CODE_FFMPEG_NOT_SUPPORTED = -469,    /* ffmpeg不支持 */
    ERROR_CODE_LIBRTMP_NOT_SUPPORTED = -468,   /* librtmp不支持 */

    ERROR_CODE_MERGER_MUST_BE_FIRST = -400,  /* 合流模块没有放在第一位 */
    ERROR_CODE_ENCODE_MUST_BE_LAST = -399,   /* 编码模块没有放在最后一位 */
    ERROR_CODE_MODULE_NUMBER = -398,         /* 模块数量不合法 */
    ERROR_CODE_LOADING_FAILED = -397,        /* 依赖库加载失败 */

    ERROR_CODE_END  = -50,     /* -1 到 -50 保留给上层接口使用 */
    ERROR_CODE_NONE = 0        /* 没有错误 */
};

enum MEDIA_SAMPLERATE {
    MEDIA_SAMPLERATE_BEGIN = 0,
    MEDIA_SAMPLERATE_8000HZ = MEDIA_SAMPLERATE_BEGIN,
    MEDIA_SAMPLERATE_11025HZ,
    MEDIA_SAMPLERATE_16000HZ,
    MEDIA_SAMPLERATE_32000HZ,
    MEDIA_SAMPLERATE_44100HZ,
    MEDIA_SAMPLERATE_48000HZ,
    MEDIA_SAMPLERATE_96000HZ,
    MEDIA_SAMPLERATE_END = MEDIA_SAMPLERATE_96000HZ
};

enum MEDIA_TRACK_TYPE {
    MEDIA_TRACK_UNKNOWN = -1,  ///< Usually treated as AVMEDIA_TYPE_DATA
    MEDIA_TRACK_VIDEO,
    MEDIA_TRACK_AUDIO,
    MEDIA_TRACK_DATA,          ///< Opaque data information usually continuous
    MEDIA_TRACK_SUBTITLE
};

enum MEDIA_MODULE_TYPE {
    MEDIA_MODULE_UNKNOWN = -1,
    MEDIA_MODULE_IN_STREAM,       /* 输入源模块 */
    MEDIA_MODULE_OUT_STREAM,      /* 输出模块 */
    MEDIA_MODULE_DECODE,          /* 解码模块 */
    MEDIA_MODULE_ENCODE,          /* 编码模块 */
    MEDIA_MODULE_WATERMARK,       /* 水印模块 */
    MEDIA_MODULE_MERGER,          /* 合流模块 */
    MEDIA_MODULE_FILTER           /* 预处理模块，比如视频裁剪、音频重采样 */
};

enum MEDIA_IN_STREAM_TYPE
{
    MEDIA_IN_STREAM_TYPE_UNKNOWN = -1,
    MEDIA_IN_STREAM_TYPE_VIDEO_CAPTURE,  /* 视频采集，url地址对应视频设备id */
    MEDIA_IN_STREAM_TYPE_AUDIO_CAPTURE,  /* 音频采集，url地址对应音频设备id*/
    MEDIA_IN_STREAM_TYPE_FFMPEG,         /* 用ffmpeg动态库打开输入源，url地址
                                            对应的是文件或者流媒体 */
    MEDIA_IN_STREAM_TYPE_RTMP,           /* rtmp流输入 */
    MEDIA_IN_STREAM_TYPE_MP4,            /* mp4文件输入 */
    MEDIA_IN_STREAM_TYPE_PROXY           /* 读取会议用户的音视频数据，url地址
                                            对应的是会议用户的actor id */
    //MEDIA_IN_STREAM_TYPE_DATA_FROM_FILE
};

enum MEDIA_DECODE_TYPE
{
    MEDIA_DECODE_TYPE_UNKNOWN = -1,
    MEDIA_DECODE_TYPE_FFMPEG_AUDIO,
    MEDIA_DECODE_TYPE_FFMPEG_VIDEO,
    MEDIA_DECODE_TYPE_AAC,
    MEDIA_DECODE_TYPE_H264,
    MEDIA_DECODE_TYPE_OPUS
};

enum MEDIA_ENCODE_TYPE
{
    MEDIA_ENCODE_TYPE_UNKNOWN = -1,

    /* audio */
    MEDIA_ENCODE_TYPE_PCMA = 0,
    MEDIA_ENCODE_TYPE_PCMU,
    MEDIA_ENCODE_TYPE_AAC,
    MEDIA_ENCODE_TYPE_LIBFAAC,
    MEDIA_ENCODE_TYPE_MP3,

    /* video */
    MEDIA_ENCODE_TYPE_VP9 = 10,
    MEDIA_ENCODE_TYPE_H264,
    MEDIA_ENCODE_TYPE_H265,
    MEDIA_ENCODE_TYPE_H264_SVC
};

enum MEDIA_FILTER_TYPE
{
    MEDIA_FILTER_TYPE_UNKNOWN = -1,
    MEDIA_FILTER_TYPE_RESAMPLER,        /* webrtc 音频重采样 */
    MEDIA_FILTER_TYPE_FFMPEG_RESAMPLE,  /* ffmpeg 音频重采样 */
    MEDIA_FILTER_TYPE_VIDEO_SCALER      /* 视频裁剪 */
};

enum MEDIA_MERGER_TYPE
{
    MEDIA_MERGER_TYPE_UNKNOWN = -1,
    MEDIA_MERGER_TYPE_AUDIO_MERGER,
    MEDIA_MERGER_TYPE_VIDEO_MERGER,
    MEDIA_MERGER_TYPE_MULTICHANNEL_AUDIO
};

enum MEDIA_MERGER_LAYOUT
{
    MEDIA_MERGER_LAYOUT_UNKNOWN = -1,

    /* self defined */
    MEDIA_MERGER_LAYOUT_SELF_DEFINED,

    /* intellegence */
    MEDIA_MERGER_LAYOUT_INTELL_FREE
};

enum MEDIA_OUT_STREAM_TYPE
{
    MEDIA_OUT_STREAM_TYPE_UNKNOWN = -1,

    /* device */
    MEDIA_OUT_STREAM_TYPE_VIDEO_RENDER = 0,
    MEDIA_OUT_STREAM_TYPE_AUDIO_PLAYOUT,

    /* file */
    MEDIA_OUT_STREAM_TYPE_DATA_TO_FILE = 5,
    MEDIA_OUT_STREAM_TYPE_MP4,
    MEDIA_OUT_STREAM_TYPE_AVI,
    MEDIA_OUT_STREAM_TYPE_WAV,

    /* web */
    MEDIA_OUT_STREAM_TYPE_RTMP = 15,

    /* other */
    MEDIA_OUT_STREAM_TYPE_CALL_BACK
};

enum MEDIA_WATERMARK_TYPE
{
    MEDIA_WATERMARK_TYPE_UNKNOWN = -1,
    MEDIA_WATERMARK_TYPE_TEXT,
    MEDIA_WATERMARK_TYPE_TIMESTAMP,
    MEDIA_WATERMARK_TYPE_PICTURE
};

/* the callback function of output stream 
   type MEDIA_OUT_STREAM_TYPE_CALL_BACK */
typedef void(*PFN_OUT_STREAM_CALLBACK)(
    const char* url,     /* url in struct media_outstream_ctx_t */
    void* object,        /* callback object */
    unsigned char* payload,       /* data */
    int payload_size,    /* data size */
    int is_video,        /* 1 - video, 0 - audio */
    int width,           /* width of video */
    int height,          /* height of video  */
    int sample_rate,     /* sample rate of audio  */
    int channels);       /* channel number of audio */

enum MEDIA_MESSAGE_CODE {
    MESSAGE_CODE_BEGIN = 0,
    MESSAGE_CODE_NONE = MESSAGE_CODE_BEGIN,
    MESSAGE_CODE_EOF = 99,
    MESSAGE_CODE_END
};

enum MEDIA_MESSAGE_SOURCE_TYPE {
    MESSAGE_SOURCE_TYPE_GENERAL = 0,
    MESSAGE_SOURCE_TYPE_INPUT,
    MESSAGE_SOURCE_TYPE_PROCESS,
    MESSAGE_SOURCE_TYPE_OUTPUT
};

/* the message callback function of general process */
typedef void(*PFN_MESSAGE_CALLBACK)(
    MEDIA_MESSAGE_SOURCE_TYPE type,
    int id,
    MEDIA_MESSAGE_CODE msg);

#endif // !_GENERAL_DESIGN_MEDIA_FLOW_C_TYPE_H_